### PR TITLE
Remove Subtitle Highlight

### PR DESCRIPTION
**Pull request by onesounds**
https://github.com/Flow-Launcher/Flow.Launcher/issues/68

1. I think the highlight of the path part is the made bad UI/UX design and functionally unnecessary. if highlight is blue, it spread blue character whole window. it made ugly design. This also destroys the highlight visibility of the title area. 
2. For the same reason, I think this function does not require on/off setting and should be erased.
3. The highlight of the title area must exist. (It is a feedback on whether the query worked normally.) I don't erase this part.

I first pr considered on/off setting, but I changed my mind. It's right to just erase this.

Tested:
- Everything plugin

TODO:
REMOVE FROM DOC https://github.com/Flow-Launcher/docs/blob/main/API-Reference/Flow.Launcher.Plugin/result.md

### CODE REVIEW

**Comment by jjw24** [comment]
which plugin has highlighting on subtitle?

also we need to remove the code too as this is only removal of the view

**Comment by onesounds** [comment]
> which plugin has highlighting on subtitle?

I looked around and there is no plug-in that uses this part specifically.

> also we need to remove the code too as this is only removal of the view

This part operates in the highlight converter.  Compared to the query, the code that puts colors in is used in duplicate in two places: title. In other words, only the subtitle is not separately worked.  I think all you have to do is erase the view code.

**Comment by jjw24** [comment]
> I looked around and there is no plug-in that uses this part specifically.

WindowSettings plugin uses subtitle search + highlight (although highlighting is off)

>This part operates in the highlight converter. Compared to the query, the code that puts colors in is used in duplicate in two places - title and subtitle. In other words, only the subtitle is not separately worked. I think we only need to erase the view code.

@onesounds @taooceros well that's the thing, do we want to completely rip out the subtitle highlighting or just 'disable' it and keep the code behind intact?

**Comment by onesounds** [comment]
> * WindowSettings plugin uses subtitle search + highlight (although highlighting is a bit off)
> * Everything plugin uses subtitle highlighting
> * Sys plugin uses subtitle search + highlight

I didn't think it was a function to "use" highlights. Highlight is just to indicate the matched letters. I only considered the possibility of some different kind of function in this part. For example, in the case of a home assistant plug-in, the highlights operate differently depending on on on/off. Of course, this plug-in doesn't work like that.

> Searching WindowSettings subtitle might be useful if you want to find all settings related to e.g. Privacy

The same applies to other plug-ins. Although not in name, there may be cases where it matches in path.

This function is a function that tells you which part matches the user's search intention when searching.  However, in general, it often appears overlapping in the path area, which damages the visual design. Also, erasing this function does not damage the actual path search results, This is ultimately the same as Title Highlight, but considering the user's general search intention, it is correct that highlights exist only in Title. If we intended to search for Subtitle, we wouldn't question the search results even if we didn't show the highlights Also, even if it was not intended to be so, there is no reason to question the current search results. This is because the search accuracy is high. This function has a reason to exist if there are really often unintended search results, but in my opinion, it does not exist.

> @onesounds @taooceros well that's the thing, do we want to completely rip out the subtitle highlighting or just 'disable' it and keep the code behind intact?

Your intention is understood by me as 'delete unused code'. However, this highlight code is just a code that checks and highlights whether the designated text block matches the query. How can we take out the subtitle highlight? We should use Title Highlight. Is it possible to separate only the subtle highlight?

**Comment by jjw24** [comment]
> Your intention is understood by me as 'delete unused code'. However, this highlight code is just a code that checks and highlights whether the designated text block matches the query. How can we take out the subtitle highlight? We should use Title Highlight. Is it possible to separate only the subtle highlight?

yeah that's what i mean, take out the code that offers the subtitle highlighting (they are also found in the api so we need to deprecate the method as well).

> This function is a function that tells you which part matches the user's search intention when searching. However, in general, it often appears overlapping in the path area, which damages the visual design. Also, erasing this function does not damage the actual path search results, This is ultimately the same as Title Highlight, but considering the user's general search intention, it is correct that highlights exist only in Title. If we intended to search for Subtitle, we wouldn't question the search results even if we didn't show the highlights Also, even if it was not intended to be so, there is no reason to question the current search results. This is because the search accuracy is high. This function has a reason to exist if there are really often unintended search results, but in my opinion, it does not exist.

sorry for the confusion, i meant, subtitle search will be kept, but remove subtitle highlighting and yes i agree, search accuracy is high enough you wont need to search the subtitle most of the time.

Just so we are on the same page, when user search something like this, it should be fine that 'computer' in the subtitle is no longer highlighted:

image

**Comment by onesounds** [comment]
> yeah that's what i mean, take out the code that offers the subtitle highlighting (they are also found in the api so we need to deprecate the method as well).

OK. I didn't know there was one in API. If so, it would be better to remove the code from the relevant plug-in, and if so, it is not simple. It's not urgent, so let's proceed slowly.

**Comment by jjw24** [comment]
hmm this kind of searches wont have any highlighting after removal:

image

**Comment by taooceros** [comment]
> hmm this kind of searches wont have any highlighting after removal:
> 
> image

I think it is ok? the title is enough to tell what the result will do. The subtitle highlight is like something that user won't notice.

**Comment by JohnTheGr8** [comment]
Is there no UI fix to this issue? Maybe a more subtle highlight in the subtitle (say, bold instead of blue) ? Removing this entirely seems like a drastic measure...

> 
> I think it is ok? the title is enough to tell what the result will do. 

The point is to also see why a result matched the typed query...

>
> The subtitle highlight is like something that user won't notice.

Disagree, but I might be biased since I added this a long, long time ago (5+ years, time flies...)

**Comment by onesounds** [comment]
Hi, I know you are an old man in this repo. Nice to meet you. 

> Is there no UI fix to this issue? Maybe a more subtle highlight in the subtitle (say, bold instead of blue) ? Removing this entirely seems like a drastic measure...

There is no setting. I think it is unnecessary.

>The point is to also see why a result matched the typed query...

Why should the user know which part was matched for typed query? If this is really necessary, we'd rather remove the highlights in the all area, and just show the score.

- One of the important rules of modern design is to subtract unnecessary things as much as possible. We shouldn't try to show all the information. 


- In general, the user searches based on the title area.
- If the search result is correct, the user does not need to know what was matched.
- Adding highlights to the subtitle area reduces the highlighting effect of the highlight. In my standard, this is the same as applying Bold to the entire document because the contents of the document as a whole are important. It's not aesthetically good either. I think the highlight of the subtle area reduces the readability of the search results

- For example,  https://github.com/Flow-Launcher/Flow.Launcher/pull/835 in the case of an app, I did not display the path at all. In this case, the user may not see an unnecessary path, and from the user's point of view, the user may feel that the search result is an App.

- In this case, as in the example of jjw, a search result with no highlights may be displayed. However, this is a rare case in general use experience. and indicating that itself a 'search result based on the subtitle', and the user can feel it.

- Other programs don't use highlights in the subtitle area. This is not our feature, our disadvantage.

image

image

image

image

image

image

image
⬆️ For your information, this program is the ugliest program and is similar to our 1.8 version.

**Comment by JohnTheGr8** [comment]
> I know you are an old man😋 
> 

I know that, too 😢 

> 
> Why should the user know which part was matched for typed query? If this is really necessary, we'd rather remove the highlights in the all area, and just show the score.

I mention this as an example, because I remember it as the main reason people requested this feature back in the day.

> 
>     * In general, the user searches based on the title area.
>     * If the search result is correct, the user does not need to know what was matched.

You assume that plugins are searching things, which is not always the case... The calculator plugin is not searching things, the Spotify plugin is not always searching things, and so on... There has to be some creative/practical use of highlighting the subtitle other than to show a search match... Why completely kill that possibility?

> 
>     * One of the important rules of modern design is to subtract unnecessary things as much as possible. We shouldn't try to show all the information.

This project is supposed to target "power users", and modern design is very much not afaik 😛 

> [...]

All I'm arguing for here is: why not just go with the original plan? add a toggle, make it off by default...?

**Comment by onesounds** [comment]
>I mention this as an example, because I remember it as the main reason people requested this feature back in the day.

At that time, I don't know why users requested it. However, it may have been necessary in that the results were not appropriate. However, the search results are excellent now. I don't think users have come up with the right solution.

> You assume that plugins are searching things, which is not always the case... The calculator plugin is not searching things, the Spotify plugin is not always searching things, and so on... There has to be some creative/practical use of highlighting the subtitle other than to show a search match... Why completely kill that possibility?

Currently, there is no plug-in using such a function. There is a possibility, but if it is a plug-in with such a possibility, I think it is better to use it more in other factors. In places such as icons and title areas. Giving a degree of freedom in this area undermines design consistency.

> This project is supposed to target "power users", and modern design is very much not afaik 😛
I agree with the saying that it is a project for power users. However, I don't think this part is necessary even for a power user. And modern power users value design more. 😂

>All I'm arguing for here is: why not just go with the original plan? add a toggle, make it off by default...?

I saw the code, and it has such a difficult structure to apply. We need to make a new highlight converter. I concluded that the value for the cost was low. If you make it, it doesn't matter if this function goes into setting. how about that?

**Comment by jjw24** [comment]
> This project is supposed to target "power users", and modern design is very much not afaik

I would say design is still very much important whilst this project targets power users, it would also be a win if we could get beginner to intermediate users on board too.

I always was under the impression that the highlighting was only implemented to help users see how a query is matched. @JohnTheGr8 i suppose the functionality could have further usage, we can always reimplemented specifically for that potential future usage, which will be better designed than to re-use the existing structure.

Worst case we can just bring back the code again from the commit history.

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
