### PR TITLE
Fix crash when user does not have access to registry startup keys

### LINKED ISSUE #1269: failed to launch- registry access error
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 07/09/2022 07:23:56
Exception:
System.Security.SecurityException: Requested registry access is not allowed.
   at Microsoft.Win32.RegistryKey.InternalOpenSubKeyCore(String name, Boolean writable)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Flow.Launcher.SettingWindow.StartupSet() in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 81
   at Flow.Launcher.App.AutoStartup() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 112
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 99
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 50
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### LINKED ISSUE #1281: Error when launching Flow launcher- Set registry error for startup
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 07/19/2022 09:21:52
Exception:
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValueCore(String name, Object value, RegistryValueKind valueKind)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value)
   at Flow.Launcher.SettingWindow.SetStartup() in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 70
   at Flow.Launcher.SettingWindow.OnAutoStartupChecked(Object sender, RoutedEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 59
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ToggleButton.OnChecked(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ToggleButton.OnIsCheckedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at Flow.Launcher.Helper.SingletonWindowOpener.Open[T](Object[] args) in C:\projects\flow-launcher\Flow.Launcher\Helper\SingletonWindowOpener.cs:line 21
   at Flow.Launcher.PublicAPIInstance.<OpenSettingDialog>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 106
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Flow.Launcher.PublicAPIInstance.OpenSettingDialog() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 104
   at Flow.Launcher.Plugin.Sys.Main.<Commands>b__14_11(ActionContext c) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Sys\Main.cs:line 259
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_9(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 207
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### LINKED ISSUE #1282: Handle exception thrown when account used to run flow does not have registry access
Instead of throwing exception when user does not have registry access, handle it and notify the user when unable to set flow to startup with system.

### LINKED ISSUE #1300: Requested registry access is not allowed
[2022-07-29.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9219324/2022-07-29.txt)

Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 07/29/2022 18:57:37
Exception:
System.Security.SecurityException: Requested registry access is not allowed.
   at Microsoft.Win32.RegistryKey.InternalOpenSubKeyCore(String name, Boolean writable)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Flow.Launcher.SettingWindow.RemoveStartup() in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 79
   at Flow.Launcher.SettingWindow.OnAutoStartupUncheck(Object sender, RoutedEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 68
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ToggleButton.OnUnchecked(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ToggleButton.OnIsCheckedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Controls.Primitives.ToggleButton.OnToggle()
   at System.Windows.Controls.Primitives.ToggleButton.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### PR DESCRIPTION
**Pull request by nachmore**
Instead log an error about non-critical functionality and continue on.

Close #1269, close #1300, close #1282, close #1281

Note: `Constant.ExecutablePath` cannot be `null`, so also simplified the `if`.

### CODE REVIEW

**Comment by taooceros** [comment]
Since you are on this part of code, is it possible to refactor it to a command in the viewmodel? So it would be possible to access the IPublicAPI to show a small notice about this error.

If not, I think it is possible to show the notification as well by accessing the helper directly.

**Comment by taooceros** [comment]
At the same time, if flow cannot access the registry, maybe set the auto startup as false? Thanks

**Comment by nachmore** [comment]
I did a small refactor, which makes sense especially since `App.xaml.cs` was [calling into `SettingWindow.xaml.cs`](https://github.com/Flow-Launcher/Flow.Launcher/blob/dev/Flow.Launcher/App.xaml.cs#L114) to set auto startup. But:

1. The `IPublicAPI` that you mention is not available to the ViewModel, it's only on the Window itself (`API`), so for now I've left the logging
2. I don't think it makes sense to display a visual error message on startup if startup can't be set, but possibly if it fails to set in settings?
3. I can flip the setting if set up fails, but not sure that's the right behaviour versus just continuing to try in case it's transient?

**Comment by taooceros** [comment]
> The IPublicAPI that you mention is not available to the ViewModel, it's only on the Window itself (API), so for now I've left the logging

I don't remember exactly the code, but even if it is not available, you can send the notification via the NotificationHelper (If I recall the name correctly) ?

> I don't think it makes sense to display a visual error message on startup if startup can't be set, but possibly if it fails to set in settings?

Maybe disable autostartup by default? And add the option for setting in the widget window, then we can simply call the set startup based on the change of the value of the field (which means we don't need code behind ui).

> I can flip the setting if set up fails, but not sure that's the right behaviour versus just continuing to try in case it's transient?

Maybe do it in the setter. Just don't set anything when it fails (if we use the pattern I mention before).

Otherwise the other code looks good for me. Thanks

**Comment by nachmore** [comment]
I updated with Notification usage, a new string in translation. Not sure what the new string process is, so just added it to everything for now.

**Note:** I saw that you edited `Fixes` to `Close` - is that stylistic? `Fixes` will also close the linked issue when merged.

**Comment by taooceros** [comment]
I just add another closes since github don't support close issues separated by comma.

**Comment by taooceros** [comment]
Oh by the way you don't have to add the strings in every i18n files. Only added it to the en.xaml will be fine, and others will be added via the integration.

**Comment by taooceros** [comment]
> Maybe disable autostartup by default? And add the option for setting in the widget window, then we can simply call the set startup based on the change of the value of the field (which means we don't need code behind ui).

Let me show you what I mean here in another pr.

**Comment by taooceros** [comment]
I haven't tested but this is the idea.

**Comment by taooceros** [comment]
@nachmore do you want to take a quick debug on whether this work? I think it feels like a cleaner way.
Thank you!

**Comment by nachmore** [comment]
Sorry for the delay, very busy period :) Found some time today; moved to the direct binding model.

**Comment by taooceros** [comment]
> Sorry for the delay, very busy period :) Found some time today; moved to the direct binding model.

No worries. Just take your time.

**Comment by nachmore** [comment]
Ok, merged & this should be it!

**Review by taooceros — APPROVED** [review]

**Comment by taooceros** [comment]
Thank you for the work!

**Pull request merged**
