### PR TITLE
Optimize Exception Handling and Log

### PR DESCRIPTION
**Pull request by taooceros**
1. Introduce Demystifier library to make stacktrace more readable. https://github.com/benaadams/Ben.Demystifier
2. Make QueryResult Method async void to allow exception thrown, which will trigger the report window on runtime.
3. Use ExceptionDispatchInfo in Log.Exception to preserve stacktrace
4. Make NLog log in async, and make Log.Exception not implemented synchronously.
5. Use NLog's exception layout renderer to render exception.
6. Use NLog's OutputDebugStringTarget to print to debug window
7. Change layout to `${logger}->${time}|${level}|${message}` (need discussion)    (Exception layout is similar but too more new line is added before and after Exception block)
    - [x] `PluginManager->21:40:16.0845|Debug|"QueryForPluginAsync"|"Cost for System Commands <14ms>"|`
8. Replace all "prefix|UnPrefix" message to call overload that allow a className and methodName
9. Use Conditional("DEBUG") for Debug method in logger.

The Exception block has been simplified to only Exception.ToString, because that will include message, Exception Type, and Stacktrace. I don't believe extra HResult or TargetSite will help us debugging.

TODO:
- [ ] Unify Program Logger

Some Discussion
- [x] Do we want every exception thrown by plugin to report in a report window? (if not, do we want a message to notice user?)

Future (need discussion)
- [ ] Make Logging system not static class but with per instance logger (which allows NLog to catch callsite)

### CODE REVIEW

**Comment by jjw24** [comment]
> Do we want every exception thrown by plugin to report in a report window? (if not, do we want a message to notice user?)

For now maybe report window as long as the link to report it is to the plugin's website not flow launcher unless they are default plugins. Reason is i would rather plugin devs be aware of the issue so they could fix it.

**Comment by jjw24** [comment]
> Make Logging system not static class but with per instance logger (which allows NLog to catch callsite)

what do you mean callsite?

**Comment by taooceros** [comment]
> > Make Logging system not static class but with per instance logger (which allows NLog to catch callsite)
> 
> what do you mean callsite?

If the log is logged directly. NLog allows to record caller information (like PluginManager.QueryAsync), so we won't need to record that separately.

**Comment by jjw24** [comment]
> > > Make Logging system not static class but with per instance logger (which allows NLog to catch callsite)
> > 
> > 
> > what do you mean callsite?
> 
> If the log is logged directly. NLog allows to record caller information (like PluginManager.QueryAsync), so we won't need to record that separately.

Perfect, as long as it records the calling method

**Comment by taooceros** [comment]
> Perfect, as long as it records the calling method

Yeah, that's why currently we cannot do that, because we Log via another method which will change the callsite.

Maybe we can simply expose a readonly logger for people to use.

**Comment by jjw24** [comment]
👍 sounds good

**Comment by taooceros** [comment]
Hmmm NLog's document suggests that callsite can be expensive (include a stacktrace tracking), but they are improving it in NLog 5.0. Maybe currently it would be better to still record caller by ourselves.

**Comment by jjw24** [comment]
Damn, ok sounds good

**Comment by taooceros** [comment]
Another question is, should we removed the manual message. "prefix|unprefix", while prefix means classname and methodname, and direct all usage to `Log.${Level}(message, classname, methodname[CallerMemberName])`?

**Comment by jjw24** [comment]
yes 👍

**Comment by taooceros** [comment]
Done

**Comment by pc223** [comment]
> > Do we want every exception thrown by plugin to report in a report window? (if not, do we want a message to notice user?)
> 
> For now maybe report window as long as the link to report it is to the plugin's website not flow launcher unless they are default plugins. Reason is i would rather plugin devs be aware of the issue so they could fix it.

I vote yes 👍  on this. Make sure users know something break _and_ where to get help is good. 

Should the report window have logs.txt file content and have a button to copy the logs too? 

I think it's better that Flow exposes the logs file a bit more. I see a lot of users have hard time to find the logs file, especially with non-portable mode, the logs file path is really...long and obscure.

I'm thinking of something like this 🤓

image

**Comment by jjw24** [comment]
Please resolve conflict.

A fair bit of changes here, what have you tested so far?

Do we want this in 1.8.0?

> I think it's better that Flow exposes the logs file a bit more. I see a lot of users have hard time to find the logs file, especially with non-portable mode, the logs file path is really...long and obscure.

@pc223 1.8.0 has command to open log file location directly, let me know if it's sufficient

**Comment by taooceros** [comment]
> Do we want this in 1.8.0?

At least part of it, including @pc223 's point.

**Comment by taooceros** [comment]
I haven't notice this one when reviewing the last change. Why do we need to include another JsonStorage?

**Comment by jjw24** [comment]
That one is because in the old infra dll it looks for JsonStrorage class, the incorrectly spelled JsonStorage

**Comment by taooceros** [comment]
> That one is because in the old infra dll it looks for JsonStrorage class, the incorrectly spelled JsonStorage

Oh, got you. I didn't notice the typo.

**Comment by taooceros** [comment]
> @pc223 1.8.0 has command to open log file location directly, let me know if it's sufficient

I won't consider that's enough because currently users won't know when exception is thrown (unless the exception is inside the core part of Flow, which is the less likely part exception is being thrown).
It would be better to expose the exception to users so that they know something is not working and can report it.

**Comment by taooceros** [comment]
> A fair bit of changes here, what have you tested so far?

1. Log is working correctly (NLog's async wrapper should not cause some weird issue)
2. Everything plugin is working
    - [ ] Check whether some api has been removed
3. Error window is going to appear when an error from PluginManager is thrown.

**Comment by pc223** [comment]
> > @pc223 1.8.0 has command to open log file location directly, let me know if it's sufficient
> 
> I won't consider that's enough because currently users won't know when exception is thrown (unless the exception is inside the core part of Flow, which is the less likely part exception is being thrown).
> It would be better to expose the exception to users so that they know something is not working and can report it.

Agreed 👍 A Msgbox error/warning is really needed, silently crash, or just doesn't launch is pretty bad UX.

 `Wox` had a reputation of being slow and crash randomly, I think mainly because a lot of exceptions silently written in logs but not notify users. Sometimes that causing Wox to slow down a lot, but still functioning, leads to users think the software just "get slower" but don't report bug because they don't know it's a bug 😅

**Comment by jjw24** [comment]
> > > @pc223 1.8.0 has command to open log file location directly, let me know if it's sufficient
> > 
> > 
> > I won't consider that's enough because currently users won't know when exception is thrown (unless the exception is inside the core part of Flow, which is the less likely part exception is being thrown).
> > It would be better to expose the exception to users so that they know something is not working and can report it.
> 
> Agreed 👍 A Msgbox error/warning is really needed, silently crash, or just doesn't launch is pretty bad UX.
> 
> `Wox` had a reputation of being slow and crash randomly, I think mainly because a lot of exceptions silently written in logs but not notify users. Sometimes that causing Wox to slow down a lot, but still functioning, leads to users think the software just "get slower" but don't report bug because they don't know it's a bug 😅

agree 100%. lol i was actually just asking whether the open log location command is sufficient for helping users find the log files, not whether logging is sufficient or effective atm 😅

**Comment by pc223** [comment]
> whether the open log location command is sufficient for helping users find the log files

Oh hahaha, for this use case, it's perfect, command in this case better than UI approach (buttons in Settings) or Docs.

**Comment by pc223** [comment]
Just take a peek at your PR,  this should be `ProgramExceptionLogger` right? it failed to build in Release mode 😄 

image

**Comment by taooceros** [comment]
> Just take a peek at your PR, this should be `ProgramExceptionLogger` right? it failed to build in Release mode 😄
> 
> image

Yes you are right🤣 The refactor tool only change the piece in debug region.

**Comment by pc223** [comment]
What do you guys think about log format like this? Seems pretty neat  :smile: and the ${callsite} idea seems pretty cool too, line number is really useful, can we do that in 1.8.0? Seems a lot of refactoring to do.

```c#
            /*
             Log looks like this:
            2021Jun23 - 01:24:36.3295150+07:00 - INFO - PluginManager - InitializePlugins|"Total init cost for <Shell> is <71ms>" - 
            2021Jun23 - 01:24:36.3295150+07:00 - DEBUG - PluginManager - InitializePlugins|"Init method time cost for <Explorer> <62ms>" - 
            2021Jun23 - 01:24:36.3295150+07:00 - INFO - PluginManager - InitializePlugins|"Total init cost for <Explorer> is <70ms>" - 
            */
            const string layout = 
                @"${date:format=yyyyMMMdd - HH\:mm\:ss.fffffffK} - " +
                @"${level:uppercase=true} - ${logger} - ${message} - " +
                @"${onexception:inner=${logger}->${newline}" +
                @"${date:format=yyyyMMMdd - HH\:mm\:ss.fffffffK} - " +
                @"${level:uppercase=true}${newline}" +
                @"Message:${message}${newline}"+
                @"${exception}${newline}}";

```

**Comment by taooceros** [comment]
> What do you guys think about log format like this? Seems pretty neat 😄 and the ${callsite} idea seems pretty cool too, line number is really useful, can we do that in 1.8.0? Seems a lot of refactoring to do.
> 
> ```cs
>             /*
>              Log looks like this:
>             2021Jun23 - 01:24:36.3295150+07:00 - INFO - PluginManager - InitializePlugins|"Total init cost for <Shell> is <71ms>" - 
>             2021Jun23 - 01:24:36.3295150+07:00 - DEBUG - PluginManager - InitializePlugins|"Init method time cost for <Explorer> <62ms>" - 
>             2021Jun23 - 01:24:36.3295150+07:00 - INFO - PluginManager - InitializePlugins|"Total init cost for <Explorer> is <70ms>" - 
>             */
>             const string layout = 
>                 @"${date:format=yyyyMMMdd - HH\:mm\:ss.fffffffK} - " +
>                 @"${level:uppercase=true} - ${logger} - ${message} - " +
>                 @"${onexception:inner=${logger}->${newline}" +
>                 @"${date:format=yyyyMMMdd - HH\:mm\:ss.fffffffK} - " +
>                 @"${level:uppercase=true}${newline}" +
>                 @"Message:${message}${newline}"+
>                 @"${exception}${newline}}";
> ```

Looks good. Though I will consider it would be better to remove some white space in date wrapper. I found a padding wrapper, which can align the log level with white space. https://stackoverflow.com/questions/20655755/nlog-format-loglevel-with-whitespaces

**Comment by pc223** [comment]
> Looks good. Though I will consider it would be better to remove some white space in date wrapper. I found a padding wrapper, which can align the log level with white space. https://stackoverflow.com/questions/20655755/nlog-format-loglevel-with-whitespaces

Cool!  Line-up the level like that is much easier to see

**Comment by pc223** [comment]
@taooceros Should I commit the new logs layout to this PR? I'm not sure how to do that properly 😄 

Send PR to https://github.com/taooceros/Flow.Launcher/tree/ExceptionOpt  ?

**Comment by taooceros** [comment]
> @taooceros Should I commit the new logs layout to this PR? I'm not sure how to do that properly 😄
> 
> Send PR to https://github.com/taooceros/Flow.Launcher/tree/ExceptionOpt ?

Yes you are right.

**Comment by taooceros** [comment]
> ${callsite} idea seems pretty cool too, line number is really useful, can we do that in 1.8.0? Seems a lot of refactoring to do.

${callsite} is not included here due to performance consideration. NLog is improving it, so maybe we will use it in the future.

**Comment by pc223** [comment]
I'm experiencing extreme slowness with this PR, do you?

It's worse when users typing fast or when the plugin have slow IO (Currency plugin). Not sure why, maybe the removing of Task. Run() ?

**Comment by taooceros** [comment]
> I'm experiencing extreme slowness with this PR, do you?
> 
> It's worse when users typing fast or when the plugin have slow IO (Currency plugin). Not sure why, maybe the removing of Task. Run() ?
> 
> 

I have experienced that before. Not sure what's causing it, but I guess it's something related to debugger and exception.
Would you take a check that whether release mode still reproduce the slowness?

**Comment by pc223** [comment]
> > I'm experiencing extreme slowness with this PR, do you?
> > 
> > It's worse when users typing fast or when the plugin have slow IO (Currency plugin). Not sure why, maybe the removing of Task. Run() ?
> > 
> > 
> 
> I have experienced that before. Not sure what's causing it, but I guess it's something related to debugger and exception.
> Would you take a check that whether release mode still reproduce the slowness?

:+1: Yeah I'll test it a bit more later

**Comment by taooceros** [comment]
@pc223 I found the issue. It's a bug that I have removed `await TaskScheduler.Default;` unexpected, which is intend to replace Task.Run. I will fix that now.

**Comment by pc223** [comment]
> @pc223 I found the issue. It's a bug that I have removed `await TaskScheduler.Default;` unexpected, which is intend to replace Task.Run. I will fix that now.

I just ran a quick test, got a pretty weird problem with `await TaskScheduler.Default;`

Before this line `await TaskScheduler.Default;`, QueryText can never be whitespaces or null because of the condition in the beginning, **but**, right after that line, sometimes **QueryText becomes empty string**, leads to crash, because `RemoveOldQueryResults` expect QueryText to be not null or whitespaces.

Not sure why yet. Do you have the same problem?

**Comment by taooceros** [comment]
Let me take a look later. I haven't experienced that before.

**Comment by pc223** [comment]
> Let me take a look later. I haven't experienced that before.

Yeah, I'll update the reproduce steps later if I can, I'm not sure about reproduce  steps right now, seems to be weirdly plugins-dependent

**Comment by taooceros** [comment]
> > Let me take a look later. I haven't experienced that before.
> 
> Yeah, I'll update the reproduce steps later if I can, I'm not sure about reproduce steps right now, seems to be weirdly plugins-dependent

Hmm I am unable to reproduce it, and I don't find a place the QueryText is supposed to be empty.🤨

**Comment by pc223** [comment]
> > > Let me take a look later. I haven't experienced that before.
> > 
> > 
> > Yeah, I'll update the reproduce steps later if I can, I'm not sure about reproduce steps right now, seems to be weirdly plugins-dependent
> 
> Hmm I am unable to reproduce it, and I don't find a place the QueryText is supposed to be empty.🤨
Can you try checking QueryText right after `await TaskScheduler.Default;`? Something like this,
```C#
            // Switch to ThreadPool thread
            await TaskScheduler.Default;
            
            
            if (string.IsNullOrWhiteSpace(QueryText))
            {
                Log.Info(nameof(MainViewModel), $"Bad QueryText", nameof(QueryResults));
            }
            
```
And use Program plugin with steps like this:
1. Type: `chrome`
2. Delete: character by character
3. When the input box empty, you should got exception

You should try this couple of times

**Comment by taooceros** [comment]
Maybe it is because some weird race tracing issue, though I am still not able to reproduce it. Let me add a few checking to avoid it. I do have experienced that before from cancellation token.

**Comment by taooceros** [comment]
@pc223 give it a test?

**Comment by pc223** [comment]
> Maybe it is because some weird race tracing issue, though I am still not able to reproduce it. Let me add a few checking to avoid it. I do have experienced that before from cancellation token.

Hmm...pretty annoying these kinds of bugs haha, I'll stash this version somewhere, ping me if you want to investigate this bug in the future. I can pretty reliably reproduce this bug on my machine 😅

**Comment by taooceros** [comment]
> Hmm...pretty annoying these kinds of bugs haha, I'll stash this version somewhere, ping me if you want to investigate this bug in the future. I can pretty reliably reproduce this bug on my machine 😅

MultiThreading apps are always generating weird bugs XD

**Comment by pc223** [comment]
> @pc223 give it a test?

Just quick test it, I can't reproduce the bug anymore, seems good for now 👍

**Comment by pc223** [comment]
The logs, do you still want to line up the levels like this? Right now they're not line-up :smile:

```patch
             const string layout = 
                 @"${date:format=HH\:mm\:ss.ffffK} - " +
-                @"${level:uppercase=true} - ${logger} - ${message:l}" +
+                @"${pad:padding=-5:inner=${level:uppercase=true}} - ${logger} - ${message}" +
                 @"${onexception:${newline}${newline}" +
                     @"EXCEPTION OCCURS\: ${exception:format=tostring}${newline}}";
```

**Comment by taooceros** [comment]
> The logs, do you still want to line up the levels like this? Right now they're not line-up 😄
> 
> ```diff
>              const string layout = 
>                  @"${date:format=HH\:mm\:ss.ffffK} - " +
> -                @"${level:uppercase=true} - ${logger} - ${message:l}" +
> +                @"${pad:padding=-5:inner=${level:uppercase=true}} - ${logger} - ${message}" +
>                  @"${onexception:${newline}${newline}" +
>                      @"EXCEPTION OCCURS\: ${exception:format=tostring}${newline}}";
> ```

Sorry what do you mean by line up?

**Comment by pc223** [comment]
> > The logs, do you still want to line up the levels like this? Right now they're not line-up 😄
> > ```diff
> >              const string layout = 
> >                  @"${date:format=HH\:mm\:ss.ffffK} - " +
> > -                @"${level:uppercase=true} - ${logger} - ${message:l}" +
> > +                @"${pad:padding=-5:inner=${level:uppercase=true}} - ${logger} - ${message}" +
> >                  @"${onexception:${newline}${newline}" +
> >                      @"EXCEPTION OCCURS\: ${exception:format=tostring}${newline}}";
> > ```
> 
> Sorry what do you mean by line up?

```log
15:12:22.2924+07:00 - INFO - MainViewModel - QueryResults|"query:<st>"
15:12:22.3364+07:00 - DEBUG - PluginManager - QueryForPluginAsync|"Cost for Program <40ms>"
15:12:22.3364+07:00 - INFO - MainViewModel - QueryTask|"Done query:<st>"
15:12:22.4634+07:00 - INFO - MainViewModel - QueryResults|"query:<s>"
15:12:22.5133+07:00 - DEBUG - PluginManager - QueryForPluginAsync|"Cost for Program <46ms>"
15:12:22.5167+07:00 - INFO - MainViewModel - QueryTask|"Done query:<s>"
15:15:52.7178+07:00 - INFO  - App - OnStartupAsync|"Begin Flow Launcher startup ----------------------------------------------------"
15:15:52.7396+07:00 - INFO  - App - OnStartupAsync|"Runtime info:
```
vs this:

```log
15:15:53.8829+07:00 - INFO  - Flow.Plugin.Program.Main - InitAsync|"Preload programs cost <425ms>"
15:15:53.8829+07:00 - INFO  - Flow.Plugin.Program.Main - InitAsync|"Number of preload win32 programs <23112>"
15:15:53.8829+07:00 - INFO  - Flow.Plugin.Program.Main - InitAsync|"Number of preload uwps <33>"
15:15:53.8829+07:00 - DEBUG - PluginManager - InitializePlugins|"Init method time cost for <Program> <475ms>"
15:15:53.8829+07:00 - INFO  - PluginManager - InitializePlugins|"Total init cost for <Program> is <483ms>"
15:15:54.1343+07:00 - DEBUG - PluginManager - InitializePlugins|"Init method time cost for <Browser Bookmarks> <722ms>"
15:15:54.1343+07:00 - INFO  - PluginManager - InitializePlugins|"Total init cost for <Browser Bookmarks> is <743ms>"
15:15:54.1855+07:00 - WARN  - Flow.Plugin.Program.Win32 - LnkProgram|
```

**Comment by taooceros** [comment]
Isn't they lined up? I add the padding property🤔

**Comment by pc223** [comment]
> Isn't they lined up? I add the padding property🤔

Where is the padding in your commits? Sorry I skim them so not sure about all the changes 😝

**Comment by taooceros** [comment]
> > Isn't they lined up? I add the padding property🤔
> 
> Where is the padding in your commits? Sorry I skim them so not sure about all the changes 😝

Oh sorry I miss it when I refactor the code. I will add it soon.🤣

**Comment by jjw24** [comment]
is this pr ready for review? 

does it need to be in 1.8.0(a lot of changes across several plugins from a glance)?

**Comment by taooceros** [comment]
> is this pr ready for review? 
> 
> does it need to be in 1.8.0(a lot of changes across several plugins from a glance)?

The major changes across plugins are from the api revise. You can take a glance on it, or if that's too much for review, let me pick a few things that worth to be included in 1.8.0.

**Comment by jjw24** [comment]
> > is this pr ready for review?
> > does it need to be in 1.8.0(a lot of changes across several plugins from a glance)?
> 
> The major changes across plugins are from the api revise. You can take a glance on it, or if that's too much for review, let me pick a few things that worth to be included in 1.8.0.

Yeah I think could you please pull out a few that is worth to be included into a separate pr and let me know what you have tested with them so I don't double up with my own testing

**Comment by taooceros** [comment]
@jjw24 Do we want to include the layout change in 1.8.0?

**Comment by jjw24** [comment]
Layout change? What do you mean

**Comment by jjw24** [comment]
The log message layout?

**Comment by taooceros** [comment]
> The log message layout?

Yes

**Comment by jjw24** [comment]
Yeah sure

**Comment by jjw24** [comment]
@taooceros could you also merge dev and resolve conflict please

**Comment by taooceros** [comment]
> @taooceros could you also merge dev and resolve conflict please

Sure, will do tonight

**Comment by pc223** [comment]
> Do we want every exception thrown by plugin to report in a report window? (if not, do we want a message to notice user?)

I think we should try to push this report-window-feature to release soon, because it affects adoption of the new Python plugins template, plugin-dev should aware of exception like this (or any invalid request/response RPC)

```
18:14:57.0716+07:00 - ERROR - JsonRPCPlugin.ExecuteAsync - Traceback (most recent call last):
  File "C:\Users\user1\AppData\Roaming\FlowLauncher\Plugins\Search-MDI-2.1.1\main.py", line 13, in <module>
    from plugin.main import MDI
ModuleNotFoundError: No module named 'plugin'
```

I caught this exception while trying to install the Search-MDI plugin, it indicates the main.py missing these lines. This should not break silently 😎

```python
import sys,os
parent_folder_path = os.path.abspath(os.path.dirname(__file__))
sys.path.append(parent_folder_path)
sys.path.append(os.path.join(parent_folder_path, 'lib'))
sys.path.append(os.path.join(parent_folder_path, 'plugin'))
```

**Comment by jjw24** [comment]
> > Do we want every exception thrown by plugin to report in a report window? (if not, do we want a message to notice user?)
> 
> @taooceros @jjw24 I think we should try to push this report-window-feature to release soon, because it affects adoption of the new Python plugins template, plugin-dev should aware of exception like this (or any invalid request/response RPC)
> 
> ```
> 18:14:57.0716+07:00 - ERROR - JsonRPCPlugin.ExecuteAsync - Traceback (most recent call last):
>   File "C:\Users\user1\AppData\Roaming\FlowLauncher\Plugins\Search-MDI-2.1.1\main.py", line 13, in <module>
>     from plugin.main import MDI
> ModuleNotFoundError: No module named 'plugin'
> ```
> 
> I caught this exception while trying to install the Search-MDI plugin, it indicates the main.py missing these lines. This should not break silently 😎
> 
> ```python
> import sys,os
> parent_folder_path = os.path.abspath(os.path.dirname(__file__))
> sys.path.append(parent_folder_path)
> sys.path.append(os.path.join(parent_folder_path, 'lib'))
> sys.path.append(os.path.join(parent_folder_path, 'plugin'))
> ```

yep makes sense to me.

Could you @taooceros  merge dev again please

**Comment by taooceros** [comment]
The feature has been merged. Jsonrpc exception is suppressed for now, but will be exposed in #633

**Comment by taooceros** [comment]
The only thing left is the exception api refractor. Probably do a clean one will be easier than merging it, but anyway, I will take a try later.

**Comment by jjw24** [comment]
@taooceros when you get a chance, could you merge dev in, i gave it a shot but still had many differences i am unsure of, so i reverted back.

**Comment by jjw24** [comment]
@taooceros when you get a chance, could you merge dev in, i gave it a shot but still had many differences i am unsure of, so i reverted back.

**Comment by taooceros** [comment]
> @taooceros when you get a chance, could you merge dev in, i gave it a shot but still had many differences i am unsure of, so i reverted back.

Sure

**Pull request closed without merging**
