### PR TITLE
Fix opera bookmarks

### PR DESCRIPTION
**Pull request by Phoenix-**
Fix for #2598

Take "custom_root" sub-object into account.

### CODE REVIEW

**Comment by Phoenix-** [comment]
Nothing else should be affected. The behavior changes only when tag with name 'custom_root' is encountered,

**Comment by taooceros** [comment]
I think it's ok for now. Could you add a comment for that? If we have more exception then we consider more abstraction.

**Comment by VictoriousRaptor** [comment]
LGTM. BTW could you please copy the problem description part of #2598 to this PR?

**Review by VictoriousRaptor — APPROVED** [review]

**Comment by Phoenix-** [comment]
Added description

**Pull request merged**
