### PR TITLE
[Plugin.Shell] Fix: The Query Box Is Not Focused When HotKey Invoked

### LINKED ISSUE #490: Plugin.Shell: The query box is not auto-focused when its hotkey is invoked
**Describe the bug/issue**
The shell plugin listens for the win+r hotkey and shows the query box when the hotkey is invoked.
However, the main window does not gain input focus.
And the user has to manually click on the query box to start typing commands.

**To Reproduce**
1. Make sure the shell plugin is enabled, and has assigned a hotkey
2. Press the hotkey
3. The query box does not have user focus

### PR DESCRIPTION
**Pull request by lzl1918**
close #490

### CODE REVIEW

**Comment by taooceros** [comment]
Thanks for the fix! Would you please take a check whether we need to call Activate()? Previously testing shows that calling Focus() is enough.

**Comment by taooceros** [comment]
By the way, would you please also add the Focus() or Activate() here?
https://github.com/Flow-Launcher/Flow.Launcher/blob/2e412a00232998546f987c034adc753c59c36b06/Flow.Launcher/CustomQueryHotkeySetting.xaml.cs#L73-L77

**Comment by lzl1918** [comment]
> By the way, would you please also add the Focus() or Activate() here?
> https://github.com/Flow-Launcher/Flow.Launcher/blob/2e412a00232998546f987c034adc753c59c36b06/Flow.Launcher/CustomQueryHotkeySetting.xaml.cs#L73-L77

Thanks. Could you please help check and review? @taooceros

**Comment by taooceros** [comment]
Thank you! I am afk today. Will review it tomorrow!

**Review by taooceros — APPROVED** [review]

**Comment by taooceros** [comment]
Thanks for the fix!

**Pull request merged**
