### PR TITLE
Fix right click & tooltip

### LINKED ISSUE #1542: BUG: Right click on search result not working
I tried to multiple OS systems and right click on search items not working.
When I right-click, the context menu does not appear.

I use dev build (Portable).

### PR DESCRIPTION
**Pull request by taooceros**
fix #1542 and tooltip not displayed

### CODE REVIEW

**Review by onesounds — APPROVED** [review]
image

**Comment by kubalav** [comment]
Right click and tooltip shows again, BUT click on items throws exception.

**Comment by VictoriousRaptor** [comment]
> Right click and tooltip shows again, BUT click on items throws exception.

Can you try to reproduce it and post the exception? I can't reproduce.

**Comment by kubalav** [comment]
Here you are:
[fl_log.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10047589/fl_log.txt)

**Comment by taooceros** [comment]
I will do a little bit more refactor and hope that may fix the issue

**Pull request merged**
