### PR TITLE
JsonRPC camelCase and Case Insensitive

### LINKED ISSUE #557: Make JsonSerialization Case Insensitive
### Discussed in https://github.com/Flow-Launcher/Flow.Launcher/discussions/546

<div type='discussions-op-text'>

<sup>Originally posted by **taooceros** July  3, 2021</sup>
Should we make JsonSerialization Case Insensitive for JsonRpcPlugin?

Currently, there are two naming policy for our python plugin. The outer response model is camel case, but the inner Result (JsonRPCResult which extends the Result class) is Pascal Case (first letter Upper). Should we mark all camel case or simply use Case Insensitive.

Any thought? @Flow-Launcher/team </div>

### PR DESCRIPTION
**Pull request by taooceros**
close #557

### CODE REVIEW

**Comment by jjw24** [comment]
What's been tested with this?

**Comment by taooceros** [comment]
> What's been tested with this?

The currency plugin and the testing plugin provided by @AnthonMS

**Comment by taooceros** [comment]
The isPrime plugin has some weird behavior. Let me take a check

**Comment by taooceros** [comment]
It behaves weird because it doesn't provide subtitle for valid prime number. It is reproducible in current pre-release.

**Comment by taooceros** [comment]
@jjw24 fix it

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
