### PR TITLE
Plugin async model

### PR DESCRIPTION
**Pull request by taooceros**
#234 #233 

1. Add two more interface, IAsyncPlugin, IAsyncReloadable to allow plugin to utilize the async model and the cancellationtoken from main thread.
2. Move Program plugin, Explorer plugin, and PluginManager plugin to the async model.

### CODE REVIEW

**Comment by JohnTheGr8** [comment]
@taooceros there's conflicts, please do a rebase and then force-push

**Comment by taooceros** [comment]
> @taooceros there's conflicts, please do a rebase and then force-push

Will do it tmr. 😊

**Comment by taooceros** [comment]
> > @taooceros there's conflicts, please do a rebase and then force-push
> 
> Will do it tmr. 😊

Done

**Comment by jjw24** [comment]
do we still need IPlugin and IReloadable and their functionalities?

**Comment by JohnTheGr8** [comment]
@taooceros Have you done any profiling to see if these changes make a difference to the better? Also, what's with all the code-formatting changes?

> 
> 
> do we still need IPlugin and IReloadable and their functionalities? As in, can they be removed?

are we breaking all plugins again?

**Comment by jjw24** [comment]
> > do we still need IPlugin and IReloadable and their functionalities? As in, can they be removed?
> 
> are we breaking all plugins again?

Have not looked at the code closely, I meant can we instead of the new interfaces, just use the existing rather than adding new ones

**Comment by taooceros** [comment]
> 
> > > do we still need IPlugin and IReloadable and their functionalities? As in, can they be removed?
> > 
> > are we breaking all plugins again?
> 
> Have not looked at the code closely, I meant can we instead of the new interfaces, just use the existing rather than adding new ones

That's possible, check out this. https://github.com/taooceros/Flow.Launcher/pull/3.
However, I don't really like the default implementation of interface, which is a compromise for compatibility. I think adding new api will be more clear.

**Comment by taooceros** [comment]
> @taooceros Have you done any profiling to see if these changes make a difference to the better? Also, what's with all the code-formatting changes?
> 
> > 
> > 
> > do we still need IPlugin and IReloadable and their functionalities? As in, can they be removed?
> 
> are we breaking all plugins again?

No we won't, that why we need the old interface. Haven't done the profiling, will do later. But not quite sure how I should do that, because I don't think this will make Plugins run quicker, but mostly allowing them to use the async/await model.

**Comment by taooceros** [comment]
> > @taooceros Have you done any profiling to see if these changes make a difference to the better? Also, what's with all the code-formatting changes?
> > 
> > > 
> > > 
> > > do we still need IPlugin and IReloadable and their functionalities? As in, can they be removed?
> > 
> > are we breaking all plugins again?
> 
> No we won't, that why we need the old interface. Haven't done the profiling, will do later, but not quite sure how I should do that, because I don't think this will make Plugins run quicker, but mostly allowing them to use the async/await model.

**Comment by jjw24** [comment]
just so we are on par with changing to a async model: 
- what's the goal of implementing this async model?
- what are the benefits we will see once switched?

**Comment by taooceros** [comment]
> just so we are on par with changing to a async model:
> 
> * what's the goal of implementing this async model?
> * what are the benefits we will see once switched?

Quite significant amount of plugin utilize internet transmission. With async model, they can easier utilize most async/await api from http library instead of needing to wait it like now.
Our current plugin lib does provide an interface for async action called IResultUpdate (although the name seems not perfect). However, it only allows us to update result async but not awaiting result async. So plugins will still need to Wait the async actions. Remember, every plugin is run in one Task, meaning manually waiting may consume the Thread from ThreadPool, and from our current result update model, Parallel.foreach won't split the execution completely, which means long waiting may block the subsequent plugin's jobs (like what we have seen in #195 that explorer plugin blocks other plugin from working).

**Comment by jjw24** [comment]
is there a way to just use IPlugin without having two and make it backwards compatible?

if not, can we just make it as a breaking change for IPlugin and plugin developers will just need to update if they will be using version 2.

What do you guys think @taooceros @JohnTheGr8

**Comment by taooceros** [comment]
> is there a way to just use IPlugin without having two and make it backwards compatible?
> 
> if not, can we just make it as a breaking change for IPlugin and plugin developers will just need to update if they will be using version 2.
> 
> What do you guys think @taooceros @JohnTheGr8

It is backwards compatible actually…… Plugins utilizes the IPlugin interface won't be affected. It just provides an extra interface for plugins to use so that they can utilize the async/await model in their query method.
There is a way to just use IPlugin interface. I just don't like it so much.

> That's possible, check out this. taooceros#3.
> However, I don't really like the default implementation of interface, which is a compromise for compatibility. I think adding new api will be more clear.

**Comment by jjw24** [comment]
can we mark IPlugin obsolete with comment to tell plugin developers to use the other plugin going forward. Also lets  add summary for both plugin so the difference is clear for those that dont do .Net. We should have future plugins built using this model instead.

**Comment by jjw24** [comment]
@taooceros the bookmark reload data doesnt seem to be updating. Add/remove bookmark => reload data. Msg appears but changes are not being updated

**Comment by taooceros** [comment]
> @taooceros the bookmark reload data doesnt seem to be updating. Add/remove bookmark => reload data. Msg appears but changes are not being updated

the plugin BrowserBookMark?

**Comment by jjw24** [comment]
> > @taooceros the bookmark reload data doesnt seem to be updating. Add/remove bookmark => reload data. Msg appears but changes are not being updated
> 
> the plugin BrowserBookMark?

yeah. Can you test

**Comment by taooceros** [comment]
> can we mark IPlugin obsolete with comment to tell plugin developers to use the other interface going forward. Also lets add summary for both interfaces so the difference is clear for those that dont do .Net. We should have future plugins built using this model instead.

You are right! Originally, I don't mean to replace the old interface because there will exist plugins that will earn seldom benefits on the async plugin model. However, simply wrap the original Query method with an Task.Run and utilize the CancellationToken will be quite useful for most plugin. I will add the obsolete for the current model.

However, what about plugins written in other language? They are using the old IPlugin model now. I don't believe any benefit they may gain by changing to async model.

**Comment by taooceros** [comment]
> > > @taooceros the bookmark reload data doesnt seem to be updating. Add/remove bookmark => reload data. Msg appears but changes are not being updated
> > 
> > 
> > the plugin BrowserBookMark?
> 
> yeah. Can you test

ok, will take a look now.

**Comment by taooceros** [comment]
> @taooceros the bookmark reload data doesnt seem to be updating. Add/remove bookmark => reload data. Msg appears but changes are not being updated

fixed, stupid error😅

**Comment by jjw24** [comment]
> > can we mark IPlugin obsolete with comment to tell plugin developers to use the other interface going forward. Also lets add summary for both interfaces so the difference is clear for those that dont do .Net. We should have future plugins built using this model instead.
> 
> You are right! Originally, I don't mean to replace the old interface because there will exist plugins that will earn seldom benefits on the async plugin model. However, simply wrap the original Query method with an Task.Run and utilize the CancellationToken will be quite useful for most plugin. I will add the obsolete for the current model.
> 
> However, what about plugins written in other language? They are using the old IPlugin model now. I don't believe any benefit they may gain by changing to async model. 

I feel like if we are going to change interface, right now it's the time because there aren't many plugins yet.

However I do want to also see what@JohnTheGr8 thinks as well. So may be hold off on this suggestion for now.

**Comment by taooceros** [comment]
> I feel like if we are going to change interface, right now it's the time because there aren't many plugins yet.

> However I do want to also see what @JohnTheGr8 thinks as well. So may be hold off on this suggestion for now.

Agree with you. Compatibility is always the thing that break potential great change.

**Comment by jjw24** [comment]
@taooceros test build is failing, could you fix it please :)

**Comment by taooceros** [comment]
> @taooceros test build is failing, could you fix it please :)

fix it

**Comment by jjw24** [comment]
using this build i couldnt load everything plugin for some reason. Havent had the time to look into, will just note it here

**Comment by taooceros** [comment]
> using this build i couldnt load everything plugin for some reason. Havent had the time to look into, will just note it here

Will take a look soon.

**Comment by taooceros** [comment]
> using this build i couldnt load everything plugin for some reason. Havent had the time to look into, will just note it here

hmmmm it works for me...... Do you have the error logged?

**Comment by jjw24** [comment]
@taooceros could you add a summary for iasyncplugin and iplugin outlining the best scenario for each usage so it's clear for developers when to use which please

**Comment by jjw24** [comment]
@taooceros please also resolve conflict

**Comment by taooceros** [comment]
> @taooceros could you add a summary for iasyncplugin, iplugin, ireloadable, iasyncreloadable outlining the best scenario for each usage so it's clear for developers when to use which please

Sure

**Comment by jjw24** [comment]
have yet review the code fully, but have been using this build for quite a while, and have had really good plugin result response and asynchronous operation performance. In the interest of moving this change forward, once the code has been reviewed, will move it into dev. 

Will keep the additional interfaces and revisit later should we want to switch. I have not found the time to profile and compare this change, maybe will do so at some point later on.

**Comment by taooceros** [comment]
> have yet review the code fully, but have been using this build for quite a while, and have had really good plugin result response and asynchronous operation performance. In the interest of moving this change forward, once the code has been reviewed, will move it into dev. 
> 
> Will keep the additional interfaces rather than switching them over, and revisit later should we want to do so as discussed above. I have not found the time to profile and compare the performance of these two types of plugin interfaces, maybe will do so at some point later on.

Good to hear that! Have it fixed the Explorer plugin issue in #274?

**Comment by jjw24** [comment]
Yeah this pr does not have the issue in that pr if that's what u mean

**Review by jjw24 — APPROVED** [review]

**Comment by jjw24** [comment]
@taooceros fixed formatting/spaces and took the opportunity to fix up the last index setting which shouldnt be set everytime https://github.com/Flow-Launcher/Flow.Launcher/pull/267/commits/d741a98112a50b81cf4551037b1d6bad6c5b0be7

**Pull request merged**
