### PR TITLE
Blanking out icons and images

### PR DESCRIPTION
**Pull request by jjw24**
Blanking out icons and images for adding logo later on.

### CODE REVIEW

**Comment by JohnTheGr8** [comment]
hmm... there's more Wox icons under `Doc/` and in the HelloWorld plugins, should we blank those out as well?

**Comment by jjw24** [comment]
For some reason I can't get the app.ico to show the new icon, can you see if it's the same case for you? Tried deleting Win 10 icon cache
image

image

**Comment by JohnTheGr8** [comment]
@jjw24 that's because it pulls the icon from the nuspec file, which uses:
>     <iconUrl>https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher/master/Flow.Launcher/Images/app.png</iconUrl>

**Comment by jjw24** [comment]
Oh ok right. Thank you.

**Comment by jjw24** [comment]
> hmm... there's more Wox icons under `Doc/` and in the HelloWorld plugins, should we blank those out as well?

done

**Pull request merged**
