### PR TITLE
Add WindowsSettings plugin

### PR DESCRIPTION
**Pull request by jjw24**
@pc223 @taooceros i have merged the WindowSettings repo into our main. Lets add/modify here, i will eventually archive and delete https://github.com/Flow-Launcher/Flow.Plugin.WindowsSettings

I have yet to look at the code, I think either we will merge ControlPanel plugin into this or vice-versa

Closes https://github.com/Flow-Launcher/Flow.Launcher/issues/266

### CODE REVIEW

**Comment by taooceros** [comment]
Just curious, how do you keep all the commit history😲

**Comment by jjw24** [comment]
@taooceros can we resolve conflict in this one please.

what's the status with this one?

do we still want to merge control panel plugin into this?

**Comment by taooceros** [comment]
> @taooceros can we resolve conflict in this one please.
> 
> what's the status with this one?
> 
> do we still want to merge control panel plugin into this?

It is almost done. Most feature in the control panel plugin should be included, except the icon.

**Comment by jjw24** [comment]
@taooceros when you get a chance, could you please resolve conflict

**Comment by jjw24** [comment]
image

Should we change the subtitle display? for example:
from 
Area "Accounts" in System settings
to
Accounts in System settings

**Comment by jjw24** [comment]
also lets change the action keyword for this plugin from $ to *

and once this is ready, we should be able to archive ControlPanel plugin right, there is nothing needed from it that we need to merge in right?

**Comment by taooceros** [comment]
Can we add another icon for control panel icon? @onesounds

**Comment by jjw24** [comment]
also how do we want to handle `Area "Area" in TaskLink`?

**Comment by onesounds** [comment]
> Can we add another icon for control panel item? @onesounds

Where do you use it?

**Comment by taooceros** [comment]
> 
> 
> 
> > Can we add another icon for control panel item? @onesounds
> 
> Where do you use it?

Result. To identify item between control panel and the windows settings.

**Comment by onesounds** [comment]
I'm asking because I don't know, but isn't the control panel showing the icon of the control panel item?

**Comment by jjw24** [comment]
ControlPanel will be archived, no longer included in the future because WindowsSettings is already including the same items

**Comment by onesounds** [comment]
Check if I understand correctly.
1. Windows setting plugin -> Searching Control Panel & Window Setting
2. Result has two type.
- Control Panel (no more using the Icon of item). so in now, there is no Icon and needed) <- it's my job.
- Window Setting (Icon is OK)
right?

**Comment by jjw24** [comment]
Yes correct.

Yep I think we can just use the existing one actually.

**Comment by onesounds** [comment]
Ok. Come to think of it, it seems strange. I'll work on it. It takes a while.

**Comment by onesounds** [comment]
Done.

ControlPanel_Small

**Comment by taooceros** [comment]
Done

**Comment by jjw24** [comment]
do we know if this `Plugins/Flow.Launcher.Plugin.WindowsSettings/Images/WindowsSettings.dark.png` icon image is being used? so far only `WindowsSettings.light.png` is used, if not, shall we delete it?

**Comment by jjw24** [comment]
> also how do we want to handle `Area "Area" in TaskLink`?

Changed the subtitle display to this, and instead of Area in TaskLink, just display 'System settings' and 'Control Panel' instead:
image

**Comment by onesounds** [comment]
> do we know if this `Plugins/Flow.Launcher.Plugin.WindowsSettings/Images/WindowsSettings.dark.png` icon image is being used? so far only `WindowsSettings.light.png` is used, if not, shall we delete it?

It is an unused icon,  you can delete it.

**Comment by jjw24** [comment]
@Flow-Launcher/team this PR is ready to be merged in, could we get an approval please.

**Review by onesounds — DISMISSED** [review]

**Comment by jjw24** [comment]
just did a push to remove the icon image, @onesounds could you approve again please

**Review by onesounds — APPROVED** [review]

**Pull request merged**
