### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by Kalaschnik**
This includes
- The squared-version logo
- App state icons (app.ico, app.png, app_error.png)
- ico has alpha channel and contains 16,32,48,64,128,256,512 sizes
- svg is minified with https://jakearchibald.github.io/svgomg/
- png files in various sizes (as ico)
- two header files for the README.MD
- the illustrator resource file

### CODE REVIEW

**Comment by jjw24** [comment]
hey @Kalaschnik , could we get these two as transparent background please
image

**Comment by Kalaschnik** [comment]
> hey @Kalaschnik , could we get these two in transparent background please
> image

Updated the PR; see `flow-header-landscape-transparent.png` and `flow-header-square-transparent.png`

**Comment by jjw24** [comment]
👍 👍 👍 

image

**Comment by Kalaschnik** [comment]
❤

**Pull request merged**
