### PR TITLE
"New" and "Installed" label in pluginstore

### PR DESCRIPTION
**Pull request by onesounds**
image

### CODE REVIEW

**Comment by jjw24** [comment]
would it look better in blue color ribbons?

**Comment by onesounds** [comment]
> 파란색 리본이 더 이쁠까요?

I will readjust the design by looking at the actual function implementation status.

**Comment by onesounds** [comment]
merged to https://github.com/Flow-Launcher/Flow.Launcher/pull/892

**Comment by jjw24** [comment]
@onesounds I can't seem to find the new and installed plugin labels in pr 892, have you merged the changes?

**Comment by onesounds** [comment]
> @onesounds I can't seem to find the new and installed plugin labels in pr 892, have you merged the changes?

yeah, merged. but This PR has only design without logic. and I was adjust design included 892.
I thought Taoo would use the design while adding functions if it had time. anyway I hide(It does not work because it does not have a function, so it is handled invisible.) in 892.

**Pull request closed without merging**
