### PR TITLE
Add quicklink to customized theme folder

### PR DESCRIPTION
**Pull request by taooceros**
Link to #201 
Add a quick link to access user theme folder.
image

If anyone would like to make it looks better, feel free to do it!

### CODE REVIEW

**Comment by taooceros** [comment]
Why do the check fail.....I think there isn't any significant change that may affect the check.

**Comment by jjw24** [comment]
> Why do the check fail.....I think there isn't any significant change that may affect the check.

 Error from CI:
C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1005: Assets file 'C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.WebSearch\obj\project.assets.json' doesn't have a target for 'netcoreapp3.1'. Ensure that restore has run and that you have included 'netcoreapp3.1

I am afk, can u check if the project websearch has the target framework in project file, pretty sure it does

**Comment by taooceros** [comment]
image
I think it does have the target framework that is as intended. This branch should not contains things about .net 5. Weird.....

**Comment by taooceros** [comment]
Oh maybe it is because that I push too fast that the restoration of project file hasn't been restored successfully. Let me push something it later and check whether that can solve this.

**Comment by JohnTheGr8** [comment]
@jjw24 @taooceros build failures should be resolved with #206

**Comment by jjw24** [comment]
Thanks for the fix both 👍 

@taooceros i changed the code to open path using FilesFolders class

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
