### PR TITLE
Implement Option to disable program description

### LINKED ISSUE #430: Option to Turn Off App Descriptions in Result List
Please implement this feature as it's badly needed. 

**THE PROBLEM**: In current state, Flow Launcher is pulling the Description of all apps/shortcuts into the results field.  This is really _unnecessary_ as power users tend to name their shortcuts appropriately. It clutters up the results list, makes it more difficult to read & identify the needed app.   I try to avoid comparing Flow Launcher to other apps, but most apps don't append additional text to the end.

image
image

image

**THE SOLUTION**

Give the user the option of turning this off as few may like it, especially newer users.
image

Once turned off, the results will display like this: 
image

### PR DESCRIPTION
**Pull request by taooceros**
resolve #430

### CODE REVIEW

**Comment by taooceros** [comment]
during debug, I found that the cpu usage is being really high. Not sure whether that's expected.

**Comment by jjw24** [comment]
can you do the test on master branch to see if same issue?

**Review by jjw24 — APPROVED** [review]

**Comment by taooceros** [comment]
> can you do the test on master branch to see if same issue?

I check it out that the slowness is because I put Explorer plugin back to global plugin. It doesn't happen in Release mode (or debug mode without debugger). I believe that's because of the error handling.

**Comment by jjw24** [comment]
> > can you do the test on master branch to see if same issue?
> 
> I check it out that the slowness is because I put Explorer plugin back to global plugin. It doesn't happen in Release mode (or debug mode without debugger). I believe that's because of the error handling.

Awesome, thank you

**Pull request merged**
