### PR TITLE
Fix fsharp plugin icon path

### PR DESCRIPTION
**Pull request by SysC0mp**
The plugin.json file was missing an IcoPath which led to errors on Flow startup.

### CODE REVIEW

**Comment by JohnTheGr8** [comment]
@SysC0mp there is no `app.png` file in the plugin's folder...

**Comment by SysC0mp** [comment]
You are right... 
It defaults currently to the missing icon image. We can leave the IcoPath either empty for now or i'll add the default app.png that is used in the HelloWorldCSharp sample, but any IcoPath is needed. Otherwise, PluginMetadata.PluginDirectory will throw an error.

**Comment by JohnTheGr8** [comment]
@SysC0mp Alright. I didn't know `PluginMetadata.PluginDirectory` throws an error when `IcoPath` is missing. Perhaps we should fix that...

**Comment by SysC0mp** [comment]
Yes, we should definitely investigate why that error appears and if it should throw that. I think we need to make sure in some way that every plugin provides a unique icon, but i am not yet sure on how to do that the best way.

**Pull request merged**
