### PR TITLE
[Program Plugin] Search programs in PATH

### LINKED ISSUE #116: Support PATH environment variables when searching for tools
**Describe the solution you'd like**

I have several tools installed with Chocolatey that end up on my path, but are not indexed by Flow Launcher, and also other tools that I drop at `~/bin`, for example. I need Flow Launcher to find those.

**Describe alternatives you've considered**

`Windows+R` and the shell plugin both work, but they don't auto complete.

**Additional context**

Using latest version, `1.1.2`.

### PR DESCRIPTION
**Pull request by VictoriousRaptor**
Resolves #116

## Changes

1. Add a option to allow Program plugin to search programs in PATH environment variable. Disabled by default (should it enabled by default?). And searching in PATH is not recursive because PATH itself is not recursive.
图片

## Tests

- [x] Works with #1476 
- [x] Can search programs (lnk, exe, ...) in PATH

### CODE REVIEW

**Comment by jjw24** [comment]
>no maximum search depth limit

You mean the search preference in settings or maximum results?

**Comment by VictoriousRaptor** [comment]
> > no maximum search depth limit
> 
> You mean the search preference in settings or maximum results?

The preference in settings.

**Comment by jjw24** [comment]
Just to confirm are we talking about the query search precision setting? Can you link me please.

**Comment by VictoriousRaptor** [comment]
> Just to confirm are we talking about the query search precision setting? Can you link me please.

https://github.com/VictoriousRaptor/Flow.Launcher/blob/2672460cc888a32907eeccdcc7e079dff6b88a67/Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml#L34

**Comment by VictoriousRaptor** [comment]
#116

**Comment by jjw24** [comment]
@VictoriousRaptor would you mind updating the description what's been tested please, and maybe remove the problems section if they are no longer please.

**Review by jjw24 — APPROVED** [review]
👍

**Pull request merged**
