### PR TITLE
Fix portable readme download link & WinGet pipeline & change Nuget publish on tag only

### PR DESCRIPTION
**Pull request by jjw24**
- Fix portable download link in readme

- Fix WinGet deployment so it occurs only on non-pr master branch builds.

- Change Nuget publish to tag only

### CODE REVIEW

**Comment by taooceros** [comment]
Does the winget update work? The check fail on last CI run

**Review by JohnTheGr8 — CHANGES_REQUESTED** [review]
Minor issue: I think it would be better to check `APPVEYOR_REPO_TAG` instead, so that the deployment to WinGet happens from the same CI build as the release deployment to Github

**Comment by jjw24** [comment]
> Does the winget update work? The check fail on last CI run

you mean the ci on the release pr? then yeah update will work because it's just failed to push the update.

**Comment by jjw24** [comment]
> Minor issue: I think it would be better to check `APPVEYOR_REPO_TAG` instead, so that the deployment to WinGet happens from the same CI build as the release deployment to Github

the release happens on push to master or is it triggered by a tag? APPVEYOR_REPO_TAG only equals true when you tag a branch and it builds right?

**Comment by jjw24** [comment]
> Minor issue: I think it would be better to check `APPVEYOR_REPO_TAG` instead, so that the deployment to WinGet happens from the same CI build as the release deployment to Github

Done

On a side note @JohnTheGr8 why are we not publishing to Nuget on tag as well? I see the build history of the 1.8.0 release tried to publish to nuget on tag build too

**Comment by JohnTheGr8** [comment]
> 
> Done

Hmm, I think this:

```ps
if ($env:APPVEYOR_REPO_BRANCH -eq "master" -and $env:APPVEYOR_REPO_TAG)
```

is equivalent to this:

```ps
if ($env:APPVEYOR_REPO_BRANCH -eq "master")
```

because it only checks if `$env:APPVEYOR_REPO_TAG` is set and not its value... I think we need to do it like this:

```ps
if ($env:APPVEYOR_REPO_BRANCH -eq "master" -and $env:APPVEYOR_REPO_TAG -eq "true")
```

> 
> On a side note @JohnTheGr8 why are we not publishing to Nuget on tag as well? I see the build history of the 1.8.0 release tried to publish to nuget on tag build too

I don't think there's a reason, we initially did nuget deployment on master builds and didn't switch to tag builds when we added github deployments later on...

**Comment by jjw24** [comment]
@JohnTheGr8 Fixed

**Review by JohnTheGr8 — APPROVED** [review]

**Pull request merged**
