### PR TITLE
use memorypack instead of binaryformatter

### PR DESCRIPTION
**Pull request by taooceros**
BinaryFormatter has been obsolete for a long time, so let's change it.

https://github.com/Cysharp/MemoryPack seems to be a nice choice. Good thing is that it supports circular reference. Though I think this is no longer a problem because uwpapp no longer reference back to their package.

The payload size seems to be slightly larger, but I think that's not a problem.

### CODE REVIEW

**Comment by taooceros** [comment]
oops I also includes change in #2416 for testing, let me remove it

**Comment by jjw24** [comment]
>The payload size seems to be slightly larger, but I think that's not a problem.

As in the final exe installer?

**Comment by jjw24** [comment]
This change touches the core code, make sure you thoroughly test, e.g. fresh install & existing plugins.

**Comment by taooceros** [comment]
> > The payload size seems to be slightly larger, but I think that's not a problem.
> 
> As in the final exe installer?

no I mean the cache. like 150k -> 200k. pretty trivial and nobody will care

**Comment by taooceros** [comment]
> This change touches the core code, make sure you thoroughly test, e.g. fresh install & existing plugins.

Na not much service is using that. Only the ImageCache and Program plugin, and both seem working fine

**Comment by jjw24** [comment]
@taooceros build failed

**Comment by taooceros** [comment]
fixed @jjw24

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
