### PR TITLE
Fix winget update causing incompatibility with always retrieving latest

### PR DESCRIPTION
**Pull request by jjw24**
This stems from the 1.8.3 release which failed with the latest winget-create version. Simplest fix is just to fix the version we are using since our release is a simple straight forward update.

### CODE REVIEW

**Comment by taooceros** [comment]
What has the latest winget changed lead to the failure?

**Comment by jjw24** [comment]
image

**Comment by Zeroto521** [comment]
My suggestion is to keep two winget versions.
One is a stable version for now to build, and another is the latest version for the future.
If the latest version building result has any error, that could warn us.

**Comment by jjw24** [comment]
There is no build involved, error comes from submission via their api. Our release is not that complicated as we only update our installer in the winget pkg repo.

I agree there should be a better way to inform of the submission failure because I only picked it up in the last release when I actively checked if the submission went through to winget. Maybe appveyor or GitHub has a way to watch pipeline failures via email,I know GitHub workflow does which is really neat.

**Comment by jjw24** [comment]
@taooceros unless there is alternative, lets get this in.

**Comment by taooceros** [comment]
OK, but I am still wondering why we cannot use the latest winget cli.

**Comment by jjw24** [comment]
@taooceros merge in? if 1.9.0 release still unable to do the update, i can spend time to take another look.

**Comment by taooceros** [comment]
> @taooceros merge in? if 1.9.0 release still unable to do the update, i can spend time to take another look.

ok

**Review by taooceros — APPROVED** [review]

**Pull request merged**
