### PR TITLE
Remove await Task.Run for IconDelegate

### PR DESCRIPTION
**Pull request by taooceros**
Let's trust plugin developer when they use that for icon
This will solve the icon blink for uwp and some other plugin that use IconDelegate.

Tested:
- [x] VScode Plugin doesn't have icon flickering

### CODE REVIEW

**Comment by jjw24** [comment]
@taooceros please list what's tested.

**Comment by jjw24** [comment]
>Let's trust plugin developer when they use that for icon

What do they need to do?

**Comment by VictoriousRaptor** [comment]
> > Let's trust plugin developer when they use that for icon
> 
> What do they need to do?

No change needed. Currently two ways to provide an icon: path to the image or a delegate.

**Comment by VictoriousRaptor** [comment]
Just found that this is not the actual problem. UWP uses IcoPath now. Blinking when typing with always preview enabled is because selected item is rapidly changing when typing.

**Comment by jjw24** [comment]
Shall we close this then?

**Comment by VictoriousRaptor** [comment]
> Shall we close this then?

it's up to tao

**Comment by taooceros** [comment]
> Shall we close this then?

Let's keep the behavior the same as before. The vscode plugin is still using the Icon delegate.

**Comment by taooceros** [comment]
> @taooceros please list what's tested.

I will test once I get back to my comp

**Review by VictoriousRaptor — APPROVED** [review]

**Pull request merged**
