### PR TITLE
Switch off the default launch on system start up

### PR DESCRIPTION
**Pull request by jjw24**
Switch off the default launch on system start up, user can set it if they wish to launch with system start up

### CODE REVIEW

**Review by onesounds — APPROVED** [review]
👼

**Comment by Garulf** [comment]
So we want Flow _not_ to auto start by default? I think most users would expect it to.

**Comment by jjw24** [comment]
i think usually programs do not auto start by default and i personally wouldnt also want any program to auto start unless i tell it too. This is also the case especially if it is portable. Auto start means editing the registry, so not everyone is fond of having a program do that without explicit permission.

**Comment by onesounds** [comment]
> 



> I think usually programs do not auto start by default and i personally wouldnt also want any program to auto start unless i tell it to. This is also the case especially if it is portable. Auto start means editing the registry, so not everyone is fond of having a program do that without explicit permission.



> I think usually programs do not auto start by default and i personally wouldnt also want any program to auto start unless i tell it to. This is also the case especially if it is portable. Auto start means editing the registry, so not everyone is fond of having a program do that without explicit permission.

How about put the setting in 'welcome screen'? it will showing when first launch. surely, default is uncheck.

**Comment by Garulf** [comment]
> I think usually programs do not auto start by default and i personally wouldnt also want any program to auto start unless i tell it to. This is also the case especially if it is portable. Auto start means editing the registry, so not everyone is fond of having a program do that without explicit permission.

Sorry deleted my comment due to some confusion... Yeah I guess that makes sense. 

I think @onesounds welcome screen idea will be the best "fix" for giving the User the option.

**Comment by jjw24** [comment]
Putting in welcome screen is great idea @onesounds

**Comment by onesounds** [comment]
Okay. I think I can work quickly because I used to make something before. Let's release 1.9 within this week and include its features.

**Pull request merged**
