### PR TITLE
Add Open Log Location command to sys plugin

### LINKED ISSUE #379: Add command to view installation error logs.
Getting this error on startup (will create separate reports for them), but having a 'pm open errorlog' or something would be helpful since there is otherwise no indication of where the logs reside or what they are called.
Screenshot 2021-03-05 12 54 03

### PR DESCRIPTION
**Pull request by taooceros**
close #379

### CODE REVIEW

**Comment by jjw24** [comment]
LGTM, version bump please

**Comment by taooceros** [comment]
> LGTM, version bump please

Sure

**Review by jjw24 — APPROVED** [review]

**Comment by jeremymeyers** [comment]
Could you add the command to view the log files to the error message window please

**Comment by taooceros** [comment]
> Could you add the command to view the log files to the error message window please

Seems reasonable, will take a try. It is not as easy as simply locate the log file location due to project separation.

**Pull request merged**
