### PR TITLE
Update to .Net 7

### PR DESCRIPTION
**Pull request by taooceros**
Upgrade to .Net 7

Tested:
- [x] my regular plugins all work without issue

### CODE REVIEW

**Comment by jjw24** [comment]
@taooceros what tests have been done?

**Comment by taooceros** [comment]
> @taooceros what tests have been done?

I am waiting for the ci build and haven't done testing.

**Comment by taooceros** [comment]
Most plugins I am using are working (I believe all shall work)

**Comment by jjw24** [comment]
@taooceros please update readme

**Comment by jjw24** [comment]
Tested following plugins:

image

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
