### PR TITLE
Add crowdin translations

### PR DESCRIPTION
**Pull request by taooceros**

### CODE REVIEW

**Comment by jjw24** [comment]
maybe keep this open for new translations that come through and then merge into dev before release

**Review by onesounds — APPROVED** [review]

**Comment by taooceros** [comment]
@smarquespt could you also take a check whether your change is included correctly? Thank you

**Review by kubalav — APPROVED** [review]

**Comment by smarquespt** [comment]
Looks good to me. A portable build would be nice to try out.

**Comment by jjw24** [comment]
Hold off on merging just yet

**Comment by jjw24** [comment]
> Looks good to me. A portable build would be nice to try out.

Yep you can try out portable of any pr by clicking on the green tick of the last commit, then go to artefacts in appveyor and download the portable zip.

**Comment by smarquespt** [comment]
> > Looks good to me. A portable build would be nice to try out.
> 
> Yep you can try out portable bulid of any pr by clicking on the green tick of the last commit, then go to artefacts in appveyor and download the portable zip.

Comments in https://github.com/Flow-Launcher/Flow.Launcher/issues/901

**Pull request merged**
