### PR TITLE
point pluginsmanifest to new api branch

### PR DESCRIPTION
**Pull request by jjw24**
use the [new branch](https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/pull/53) in PluginsManifest per [discussion](https://github.com/Flow-Launcher/Flow.Launcher/discussions/535)

### CODE REVIEW

**Comment by jjw24** [comment]
@taooceros @JohnTheGr8 as per discussion, good to go?

**Comment by taooceros** [comment]
> @taooceros @JohnTheGr8 as per discussion, good to go? 

Have you checked what @Zeroto521 says?

**Comment by jjw24** [comment]
Just saw it, ok let me think about this

**Comment by JohnTheGr8** [comment]
Has anyone tried to see what happens when Flow updates but a previously installed plugin is no longer compatible? Does new flow simply ignore it (not load it)?

**Comment by jjw24** [comment]
what scenario you are talking about ? i have tested dev branch's build with all plugins we currently have, they are all compatible

**Comment by taooceros** [comment]
> Has anyone tried to see what happens when Flow updates but a previously installed plugin is no longer compatible? Does new flow simply ignore it (not load it)?

I think it will pop out a message saying that a specific plugin is unable to load.

**Comment by jjw24** [comment]
> > Has anyone tried to see what happens when Flow updates but a previously installed plugin is no longer compatible? Does new flow simply ignore it (not load it)?
> 
> I think Flow will pop out a message saying that a specific plugin is unable to load, and disable it.

Yeah, if the plugin fails to load, that message will pop out. If flow is .net core and plugin is .net 5, the same message will pop up

**Comment by JohnTheGr8** [comment]
> Yeah, if the plugin fails to load, that message will pop up. If flow is .net core and plugin is .net 5, the same message will pop up

That's what I meant. Maybe we should be auto-updating these if possible? Or prompting the user to update it (assuming an update is available)

**Comment by jjw24** [comment]
We can't do anything for users on 1.7.2 or earlier, any changes will be 1.8.0 onwards. This scenario is not valid anyway because with the branch system, they won't be able to download unsupported plugins

**Comment by JohnTheGr8** [comment]
> 
> 
> We can't do anything for users on 1.7.2 or earlier, any changes will be 1.8.0 onwards. This scenario is not valid anyway because with the branch system, they won't be able to download unsupported plugins

What I mean is: if a plugin is installed under Flow 1.7.2 that is not compatible with 1.8.0 because of a breaking change, and the user updates their Flow to 1.8.0, the plugin will still be there in the AppData folder.... If this happens and the plugin fails to load, it would be nice to prompt the user to simply update the plugin to a version that is compatible.

**Comment by taooceros** [comment]
After the fix for everything plugin, I don't believe we have introduced some breaking change for plugin systems in 1.8.0. But that's an interesting idea.

**Comment by jjw24** [comment]
> > We can't do anything for users on 1.7.2 or earlier, any changes will be 1.8.0 onwards. This scenario is not valid anyway because with the branch system, they won't be able to download unsupported plugins
> 
> What I mean is: if a plugin is installed under Flow 1.7.2 that is not compatible with 1.8.0 because of a breaking change, and the user updates their Flow to 1.8.0, the plugin will still be there in the AppData folder.... If this happens and the plugin fails to load, it would be nice to prompt the user to simply update the plugin to a version that is compatible.

I don't think this is a necessity for 1.8.0 release, we have tested the current plugins.

This logic is a bit hard to achieve though, if we can figure out the plugin failure to load is due to lower version plugin, we need to check if a newer version is available. What if plugin load failure is because the plugin tried to write data to a protected folder? 

May be a lot faster to just help user read the error logs than to write up logic to determine the type of failure?

**Comment by jjw24** [comment]
@taooceros @JohnTheGr8 can we get this moving along and merged?

**Review by taooceros — APPROVED** [review]

**Comment by JohnTheGr8** [comment]
> I don't think this is a necessity for 1.8.0 release, we have tested the current plugins.

Testing all the plugins for every big release cannot be fun, that's all... ;)

But yeah, I think this is good to go.

**Comment by jjw24** [comment]
> > I don't think this is a necessity for 1.8.0 release, we have tested the current plugins.
> 
> Testing all the plugins for every big release cannot be fun, that's all... ;)
> 
> But yeah, I think this is good to go.

Agree, not fun haha. Let's work on your suggestion for the next release after 1.8.0

**Pull request merged**
