### PR TITLE
Update Slovak translation (Flow Launcher + plugins)

### PR DESCRIPTION
**Pull request by kubalav**

### CODE REVIEW

**Review by jjw24 — APPROVED** [review]

**Comment by jjw24** [comment]
Before merging, we need to version bump the plugins

**Comment by jjw24** [comment]
Why is this closed?

**Comment by kubalav** [comment]
IDK. I press fetch all in Git Extension and something close my PR.

**Comment by jjw24** [comment]
Looks like you did a force push, resetting your branch to current dev....

**Comment by kubalav** [comment]
Can I create new PR now?

**Comment by jjw24** [comment]
Yeah go for it. Do you know how to version bump the plugins since you are creating a new one? Literally increasing the version number in the plugin.json file of the plugins you added the translation

**Comment by kubalav** [comment]
I'm confused. Have I to bump the plugin version when I update translation?

**Comment by jjw24** [comment]
Yeah, we bump plugin version with each change, I used to do it for u :P I am just right now afk.

**Pull request closed without merging**
