### PR TITLE
[no ci] README: fix appwrite logo, md improvements

### PR DESCRIPTION
**Pull request by NoPlagiarism**
- fix [appwrite](https://appwrite.io) logotype
- Markdown improvements
	- Replace some HTML links to MD ones
	- Hotkeys table is pretty now

### CODE REVIEW

**Comment by taooceros** [comment]
Any difference in appearance?

**Comment by NoPlagiarism** [comment]
Yeah, there's also no spaces between sponsors in a row

**Comment by taooceros** [comment]
oh I mean using the markdown hyperlink

**Comment by taooceros** [comment]
@onesounds mind take a look on the spacing?

**Comment by NoPlagiarism** [comment]
> oh I mean using the markdown hyperlink

Ah, links works the same way as they did

**Review by onesounds — APPROVED** [review]

**Pull request merged**
