### PR TITLE
Release 1.8.0 | Plugin 2.0.0

### PR DESCRIPTION
**Pull request by jjw24**
Release Notes
=========

## Breaking Change
- Plugin API (Flow.Launcher.Plugin) updated to .Net 5 #228

## Features
- Install Flow via WinGet: `WinGet install "Flow Launcher"`
- New [documentation](https://flow-launcher.github.io/docs) page!
- Press F5 in query window to reload all plugin data #334
- Enable Flow's saving mechanism to be used by plugins #330 #393
- Automatic Python installation for Python plugins #319 #465 #477
- Copy the bookmark's url to clipboard via BrowserBookmarks's context menu #340 
- Improved general download efficiency #342 
- Added logging, save and load settings json files to IPublicAPI for plugins to use #341 
- IPlugin interface now inherits from IAsyncPlugin #390 
- Optimize plugins manifest downloading behavior #314
- Optimized result list queuing and updating #343 #563 
- Updated JSON-RPC model to async #331 
- Added copy command via context menu for Shell plugin #382
- Added documentation link to the usage tips section #396
- Add score bumping with query and do hashcode customized #398
- Enabled saving of Shell plugin's commands history, with option to set the display number of most used commands in result list #404
- Add API error msg method #412
- Add tips and UserData location commands for Sys plugin #415
- Run Shell plugin cmds as admin with ctrl #429
- Ctrl enter/click open Plugin's url #429
- Enable plugins to use API call to save instead of directly calling Infrastructure's save method #427
- Multiple UX/UI enhancements to WebSearch plugin #443
- Implement Option to disable program description #447
- Optimized Exception Handling and Log #532 #547
- For Explorer plugin, in addition to the main search action keyword also added action keywords to separately search for directory paths and indexed files and folders #449 #541
- Remove top and bottom margin of General tab (Settings) #483 #495
- Added the option to enable or disable auto hiding of the settings window scrollbar #440
- Added JsonRPC unit tests to ensure the model is working correctly as intended #562

## Bug fixes
- Fixed win32 app loading for Program plugin: #78 
  - Now able to retrieve the correct file path for programs in the start menu that have LNK extension, ie. Command Prompt from start menu.
  - Fix the issue where type 'cmd' does not get you Command Prompt
  - Remove ShObjldITIb.dll which was for launching applications using Application Activation Manager and loading app info using Shell Links. We now directly use the code, not needing this dll to be embedded.
  - Remove duplicate lnk program pointing to the same exe with the same description.
- Removed AppxPackagingTlb.dll used for UWP loading #79
- Fixed a bug related to operation timeout issue for Flow's version updater and WebSearch plugin #364 
- Updated json response usage in WebSearch plugin and revise access of UserSelectedRecord, Histroy, TopMost classes' setter to private #368
-  Fixed support for euler number and minor issue thrown during debug #370 
- Fixed WebSearch plugin's action keyword: #372  
  - Changed the WebSearch's google search action keyword to global as the default 
  - Fixed ordering of the plugin's result so non global action keyword matches will appear above global action keyword matches
- Re-added missing Google Scholar action keyword `sc` #376
- Fixed issue causing Flow to turn into  a vertical black line after waking from hibernation #377
- Log Location can now be accessed via Sys plugin command #380
- Fixed the issue where indexing would need to finish before Flow could continue loading the rest of startup #381 
- Fixed exclusion of Windows Index search, making it effective also for searches via file/folder names or file contents #386
- Optimized BrowserBookmarks and Calculator plugins' startup speed #389
- Increased the Settings page's default width and allow user to resize the window #395
- Allow Quick Access Links to be searched using part of the string instead of the word starting with #409
- Remove redundant QuickAccess folder nickname path #410
- Added/updated Slovak translation for plugins #419 #555 #458 #401
- Added and corrected Chinese translation #422
- Fix Plugin Indicator when more than one query term is typed #425
- Fixed Win32 & UWP's AppxManifest.xml leak #452 #488
- Fixed loading when no action keywords present for a plugin in user plugin setting #455
- Fixed duplicate query searches from same global action keywords #456
- Fix unparsed property when using Python plugins #461 #464
- Changed sequence of loading for Shell plugin to avoid null reference #460 
- Fixed JSON-RPC model issues #466 #469 #556
- Fixed query window's shadow margin not appearing at top and bottom, as well as being cut off at the corners #472
- Fixed progress bar animation, which should drop cpu usage when hidden while query is running #474
- Fixed settings window doesn't show back up when minimized in taskbar by user #484
- Fixed Context Menu bug where when no item is selected going to the context menu results in weird UX #491
- Fixed the Query Box Is Not Focused When HotKey Invoked when using Shell plugin's Win+R shortcut #489 
- Fixed possible issue with querying after loading a Python context menu #538
- Fixed the Settings window freezing after locking computer screen (Win+L) #544
- Fixed PluginsManifest constantly updating in the background when queried #550
- Removed empty entries when specifying program suffixes #552
- Fixed missing disposable call that allows plugins to do something before flow exits #561
- Fix flow's hotkey not working correctly after changing in settings #565 #570

To complete prior to release:
- update documentation for running Shell cmds as admin with ctrl
- update documentation tips Ctrl enter/click open Plugin's url

### CODE REVIEW

**Comment by deefrawley** [comment]
Can someone create a test installer to run as I can't build from source?

**Comment by jjw24** [comment]
Of course:
https://github.com/Flow-Launcher/Flow.Launcher/discussions/535

**Comment by jjw24** [comment]
@Flow-Launcher/team let's roll, one of you approve this please

**Comment by jjw24** [comment]
@Flow-Launcher/team let's roll, one of you approve this please

**Review by pc223 — DISMISSED** [review]

**Review by taooceros — DISMISSED** [review]

**Review by taooceros — APPROVED** [review]

**Pull request merged**
