### PR TITLE
Revert "Fix Window Positioning with Multiple Montiors"

### PR DESCRIPTION
**Pull request by onesounds**
Reverts Flow-Launcher/Flow.Launcher#2756

### CODE REVIEW

**Review by jjw24 — APPROVED** [review]

**Comment by jjw24** [comment]
@onesounds just so it's recorded here, what was the issue that we had to revert? 

Also does this fix the remember last position issue?

**Comment by onesounds** [comment]
- Fixed https://github.com/Flow-Launcher/Flow.Launcher/issues/2820
- Confirmed that it was fixed successfully.

I tested my PR, but merged it without testing TAOO's fix. This is both TAOO's and my fault for not testing thoroughly. I checked Taoo's commit, but nothing seemed particularly wrong and I couldn't figure out why. I chose to revert because the PR was changed based on Point2D and I can't fix it, and I don't want to ask taoo to fix it.

**Comment by onesounds** [comment]
After this, the 2320 issue is reinstated. This is a simple issue and will be worked on in a separate PR.

**Comment by jjw24** [comment]
OK so issue 2820 is fixed, but 2320 is not, shall we reopen issue 2320?

**Comment by VictoriousRaptor** [comment]
Just FYI https://github.com/microsoft/PowerToys/pull/33784 this might be related.

**Pull request merged**
