### PR TITLE
Fix UWP loading

### PR DESCRIPTION
**Pull request by jjw24**
- Remove AppxPackagingTlb.dll

### CODE REVIEW

**Comment by taooceros** [comment]
Is this branch simply remove the dll and use ComImport class to do the same job?

**Comment by jjw24** [comment]
yep

**Comment by taooceros** [comment]
LGTM, I just change the declear of out variable to inline deslearation so that it will be clearer.

**Comment by taooceros** [comment]
Let me take a test before approving it.

**Review by taooceros — APPROVED** [review]

**Pull request merged**
