### PR TITLE
Add handling of exceptions from plugins

### PR DESCRIPTION
**Pull request by taooceros**
Add exception handling thrown by plugins.

Update user error window to point to plugin's Url.

### CODE REVIEW

**Comment by jjw24** [comment]
What's this one?

**Comment by taooceros** [comment]
> What's this one?

Wrap exception come from query plugin do that somewhat redirect the exception caused by plugin to the plugin repo.

**Comment by jjw24** [comment]
Let me know when good for review.

**Comment by taooceros** [comment]
I will give it a test recently.

**Comment by taooceros** [comment]
I think it works.

**Comment by taooceros** [comment]
image

**Review by jjw24 — APPROVED** [review]
👍 👍

**Pull request merged**
