### PR TITLE
Enable non-C# plugins to use StringMatcher's scoring

### PR DESCRIPTION
**Pull request by Garulf**
Provides a new field called `FuzzyMatchString` that will override a results score with Flow's `StringMatcher.FuzzSearch` by matching the current query with the new field. 

Otherwise the field is `null` and ignored.

- [x] Fuzzymatch results
- [x] Hide results tht dont meet cutoff
- [x] Add text highlighting based on match?
- [x] Fix scores not applying if query text is the same

### CODE REVIEW

**Comment by taooceros** [comment]
I have a concern on this. What if the fuzzysearchtext is not equal to the title? Then the highlight may be weird.

**Comment by jjw24** [comment]
Sperate conversation - @taooceros is it possible to do a callback to the plugin? E.g. python plugin -> json callback object with required data i.e. search string and method to call -> flow runs the API method -> result returned back to the plugin. Do you have something like this in the V2 JsonRPC design?

**Comment by taooceros** [comment]
> Separate conversation - @taooceros is it possible to do a callback to the plugin? E.g. python plugin -> json callback object with required data i.e. search string and method to call -> flow runs the API method -> result returned back to the plugin. Do you have something like this in the V2 JsonRPC design?

that's in the original plan for V2.

**Comment by jjw24** [comment]
@taooceros we need to properly take a look at this in relation to the V2 pr, maybe this is better done there.

**Comment by taooceros** [comment]
> @taooceros we need to properly take a look at this in relation to the V2 pr, maybe this is better done there.

Well I should say yes, but it really depends on how to design the api. Exposing a string matching field is a much simpler way for plugins to use the fuzzy api (I feel like we can just match title so highligh works).

**Comment by jjw24** [comment]
Marking draft. We will enable StringMatcher to be used by non-dotnet plugins via v2 JsonRPC

**Pull request closed without merging**
