### PR TITLE
Drag and drop

### PR DESCRIPTION
**Pull request by onesounds**
**What's the PR**
- Change result items to draggable (to Desktop or Discord...)
- How it is dragged depends on the target, e.g. Windows Explorer or other file managers:
  - For Windows Explorer (Win 11), copy: Ctrl+Drag 
  - For Windows Explorer (Win 11), move: Drag

**Test case**
- Files must be moved and copied to the target location
- It should be applied where drag attachments are allowed, such as Discord.
- If it is not a file or folder, it should not be draggable.

**Todo list**
- [x] Check the UX (just drag to copy is better? in this case, move by shift+drag) 
- [x] Clean Code
- [x] Should the file's moved status be updated to the index immediately?

### CODE REVIEW

**Comment by onesounds** [comment]
Change the UX
- Drag : Copy
- Shift+Drag : Move

**Comment by jjw24** [comment]
> Should the file's moved status be updated to the index immediately

This will be automatic as Explorer's Windows Search and Everything's service should both index the new location, with the exception if Explorer's Window's search is not configured to index the new location.

**Review by jjw24 — COMMENTED** [review]
Getting this error when I ctrl drag on Windows 11 explorer, explorer and flow crashes:
image

**Comment by jjw24** [comment]
> Getting this error when I ctrl drag on Windows 11 explorer, explorer and flow crashes: image

This somehow is no longer an issue after I restarted my Visual Studio.

**Review by jjw24 — APPROVED** [review]
👍

**Pull request merged**
