### PR TITLE
Plugin activation icon

### PR DESCRIPTION
**Pull request by Garulf**
See @onesounds comment below: https://github.com/Flow-Launcher/Flow.Launcher/pull/911#issuecomment-996713960

### CODE REVIEW

**Comment by onesounds** [comment]
This PR for displaying what activated plugin.

It only showing when activated action keyword (not display general query and *) in magnify icon location. It may be a little complicated in design, but it is functionally meaningful in that it gives feedback on whether the keyword works. Also, I don't think it's harmful to the design because it's not shown in the general results.

**Comment by Garulf** [comment]
Possible to have a very fast fade and slide from right animation?

**Comment by onesounds** [comment]
> Possible to have a very fast fade and slide from right animation?

I tried it, but it didn't go well. I can do it to do it, but  It will be very complicated. 
I think it's in good condition now.

**Comment by Garulf** [comment]
Okay, didn't know how much complexity it would add.

**Comment by jjw24** [comment]
hold for 1.10

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
