### PR TITLE
Move Tasklink Name into Resource (except altName) & Glyph Icon Support

### PR DESCRIPTION
**Pull request by taooceros**
It is creating too much warning in the log file because of translation. No need for the warning because it is simply the resources doesn't exist.

### CODE REVIEW

**Comment by jjw24** [comment]
Should we perhaps change it to `if debug` to log when only debugging? Would there be a case where we need to determine why a resource is not loaded?

Also plugin version bump please

**Comment by taooceros** [comment]
> Should we perhaps change it to `if debug` to log when only debugging? Would there be a case where we need to determine why a resource is not loaded?
> 
> Also plugin version bump please

Generally it is simply because of the translation doesn't exist, which should be totally fine. We cannot distinguish this from other reason because it is simply return null.

**Comment by taooceros** [comment]
wait a moment. If it's translation issue, shouldn't be so much resources can't be found. I will check again.

**Comment by taooceros** [comment]
huh those strings are for control panel (probably for task link added by @pc223 ) I remember he adds the translation for that previously. We can add that first.

**Comment by jjw24** [comment]
> huh those strings are for control panel (probably for task link added by @pc223 ) I remember he adds the translation for that previously. We can add that first.

I thought we included his changes already

**Comment by jjw24** [comment]
> I remember he adds the translation for that previously. We can add that first.

I wasnt too invovled with the PR/changes, do you know where we can find the translations he added previously?

**Comment by taooceros** [comment]
> > I remember he adds the translation for that previously. We can add that first.
> 
> I wasnt too invovled with the PR/changes, do you know where we can find the translations he added previously?

https://github.com/pc223/MSWindowsControlPanelTaskLinks
he has added part of that here

**Comment by taooceros** [comment]
I will fix the resources by adding a english one first

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
