### PR TITLE
Add "" in FilesFolders.OpenPath to be able to open path with ','

### PR DESCRIPTION
**Pull request by taooceros**

### CODE REVIEW

**Comment by jjw24** [comment]
what's an example of this issue?

**Comment by taooceros** [comment]
image
I am unable to open this file with Explorer plugin. By adding the quotation mark, it will work. I believe this is due to the space in the path.

**Comment by jjw24** [comment]
> image
> I am unable to open this file with Explorer plugin. By adding the quotation mark, it will work. I believe this is due to the space in the path.

i tested with space in the path, it still worked.

let me try replicate your path

**Comment by taooceros** [comment]
That's quite weird... Maybe it may caused by the file name instead of path? Because seems that I will be able to open the container folder.

**Comment by taooceros** [comment]
Or maybe the reason is the `,` within the file name?

**Comment by taooceros** [comment]
Yeah test it, the issue is due to the `,` instead of space.

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
