### PR TITLE
Expand Plugin API

### PR DESCRIPTION
**Pull request by taooceros**
#220 

Expand IPublicAPI for plugin users to use.

1. StringMatcher.FuzzySearch()
2. Http.GetAsync & Http.GetStreamAsync & Http.DownloadAsync
3. Add & remove ActionKeyword

Detail Implementation require further discussion.

### CODE REVIEW

**Comment by taooceros** [comment]
@Flow-Launcher/team any idea?

**Comment by Zeroto521** [comment]
add some hooks, see https://github.com/jjw24/Wox/issues/194

> I want to be hook master.

**Comment by taooceros** [comment]
> add some hooks, see [jjw24/Wox#194](https://github.com/jjw24/Wox/issues/194)
> 
> > I want to be hook master.

emmm I am not sure what do you mean by hooking...... Do you mean that we should allow plugin to do more things other than querying?

**Comment by jjw24** [comment]
why we exposing action key word methods?

**Comment by taooceros** [comment]
> why we exposing action key word methods?

To allow plugins to have more than one actionkeyword. Currently, although we allow mutiple keywords, only internal plugins can utilize it because external plugin has no access to their actionkeywords.

**Comment by taooceros** [comment]
Also, plugins won't be available to change action keywords for other plugin since they don't know the id of other plugin.

**Comment by Zeroto521** [comment]
Exposed the system calling function process.

There would have a hook called `before_user_query`. 
It means to do something before the `query`.  
A simple example is that it could be used to log querying words.

**Comment by taooceros** [comment]
> Exposed the system calling function process.
> 
> There would have a hook called before_user_query.
> It means to do something before the query.
> A simple example is that it could be used to log querying words.

Like registering an event that will be triggered before querying? But why don't we do the job when querying?

**Comment by jjw24** [comment]
> > why we exposing action key word methods?
> 
> To allow plugins to have more than one actionkeyword. Currently, although we allow mutiple keywords, only internal plugins can utilize it because external plugin has no access to their actionkeywords.

more than one action keyword like in websearch plugin?

**Comment by taooceros** [comment]
> > > why we exposing action key word methods?
> > 
> > 
> > To allow plugins to have more than one actionkeyword. Currently, although we allow mutiple keywords, only internal plugins can utilize it because external plugin has no access to their actionkeywords.
> 
> more than one action keyword like in websearch plugin?

Yes, and in Explorer plugin.

**Comment by Zeroto521** [comment]
You should not do a stack of things in one place. And some hooks better could have global authority. before_all_user_query could do something before each plugin.

**Comment by jjw24** [comment]
i think i have also done some changes on this stringmatcher migration but got distracted. I might merge them in if  feasible and ok

**Comment by taooceros** [comment]
> You should not do a stack of things in one place. And some hooks better could have global authority. before_all_user_query could do something before each plugin.

Do you want it to be activated for plugins? Like an event, allowing plugin to do something here, that will be triggered before plugin querying every time user is querying. Or it is simply something that we just do in Flow.

**Comment by taooceros** [comment]
@Zeroto521 Let's move that discussion to #267 , since this pr is majorly focusing on the APIs lie in IPublicAPI.

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
