### PR TITLE
Remove font-family style for Chinese

### PR DESCRIPTION
**Pull request by onesounds**
**What's the PR**
- issue from https://github.com/Flow-Launcher/Flow.Launcher/issues/1425
- Removed font-family tabmenu / other windows

**Before**
image

**After**
image

**Checklist**
- There should be no impact on other language.
- It will use the default OS font, so I think there will be no problem.

### CODE REVIEW

**Comment by VictoriousRaptor** [comment]
Segoe UI is not only used in tabmenu but also elsewhere. Please fix them as well (if you are busy I can do this later, I have to sleep now:( ). i ve tested that it also affects Japanese, maybe Korean as well.

**Comment by VictoriousRaptor** [comment]
BTW it should affect some English texts on non-english locale systems. English texts in system default font on non-english systems, like Chinese, is slightly different from Segoe UI.

I think it doesn't matter cuz most people will choose their system language.

**Comment by onesounds** [comment]
When I checked, there were no more cases where Segoe UI was designated.
I checked the other Asian fonts, and it was not a problem.

If you know how to, Do as you wish.

**Comment by VictoriousRaptor** [comment]
> When I checked, there were no more cases where Segoe UI was designated. I checked the other Asian fonts, and it was not a problem.
> 
> If you know how to, Do as you wish.

There are some cases in plugins. I've created a PR to your fork.

> BTW it should affect English texts on non-english locale systems. English texts in system default font on non-english systems, like Chinese, is slightly different from Segoe UI.
> 

This is because there is no semibold weight in default Chinese font (MS YaHei UI).

**Comment by onesounds** [comment]
I missed the plugins. thanks.

> BTW it should affect English texts on non-english locale systems. English texts in system default font on non-english systems, like Chinese, is slightly different from Segoe UI.

I checked it after changing OS to another language. It didn't seem particularly problematic. It doesn'thave to be Segoe UI.

**Pull request merged**
