### PR TITLE
[Dev] Improve Clock/Date

### PR DESCRIPTION
**Pull request by onesounds**
## What's the PR
- Add some Date / Clock Formats
  - Resolve the https://github.com/Flow-Launcher/Flow.Launcher/issues/1553
- Change Date/Time format Culture info from language setting (not os)
- Change Clock/Date Style (vertical align like tray clock)
- Add Clock/Time preview in side of combobox
- Add Clock Transition when open flow
- Use Animation will control Open Clock Transition 
- Adjust Animation codes
- Remove Trigger Exit Action Style
  - In this case, clock collapsed without animation when start type.
- Adjust some clock/date style in themes
- Formatting Animation Codes

## Test Cases
- [x] The am/pm display must change depending on the flow language setting.
- [x] A preview (side combo box) of the clock/date must be reflected immediately upon change.
- [x] If both clock and date are turned on, the font size must be properly changed.
- [x] If you turn off the animation setting, the clock start animation should not behave like the search icon.
- [x] When start typing, clock/date should hide without animation

## Issue
An animation in which the clock appears when the query is initialized(query lengh 0 situation) cannot be turned off by the animation setting. It was beyond me to ensure that this part was reflected according to the setting. (I worked on this problem for 3 days... but it was not resolved.) This issue should be retried in a separate pr.

### CODE REVIEW

**Comment by VictoriousRaptor** [comment]
Is it possible to preview the formats? like showing the `13:00 Tue 10/1` in the dropdown?

**Comment by onesounds** [comment]
> Is it possible to preview the formats? like showing the `13:00 Tue 10/1` in the dropdown?

it is possible but not me. 😅 how about you?

**Comment by onesounds** [comment]
> > > Is it possible to preview the formats? like showing the `13:00 Tue 10/1` in the dropdown?
> > 
> > 
> > it is possible but not me. 😅 how about you?
> 
> maybe. I guess UI tweak is needed. the dropdown button might not be wide enough for evey language.

I can handle UI. do as u wish in this pr or new pr. I guess dropdown button will be small, but opened dropdown is no problem.

**Comment by VictoriousRaptor** [comment]
The implementation is dirty but can't come up with any better idea yet.

**Comment by taooceros** [comment]
> > Is it possible to preview the formats? like showing the `13:00 Tue 10/1` in the dropdown?
> 
> it is possible but not me. 😅 how about you?

use similar thing like combobox.Display like you have done before?

**Comment by taooceros** [comment]
> The implementation is dirty but can't come up with any better idea yet.

you are doing the same dirty implementation as me for explorer XD. I should also adjust that

**Comment by VictoriousRaptor** [comment]
> > The implementation is dirty but can't come up with any better idea yet.
> 
> you are doing the same dirty implementation as me for explorer XD. I should also adjust that

Well I can't figure out a better way yet.

**Comment by taooceros** [comment]
> Well I can't figure out a better way yet.

I will check, but I am semi-busy this week....hope I should have some passion to work more efficiently

**Comment by VictoriousRaptor** [comment]
Should be much cleaner now. One remaing issue is `CultureInfo.CurrentCulture` seems incorrect when system language is different from Flow before manually changing Flow's language.

**Comment by VictoriousRaptor** [comment]
tests:
- [x] Toggling date/time can correctly affect preview and mainwindow.
- [x] Settings can be saved.

todo:
- [ ] Fix culture info issue in initializing and updating lists. (help required)

**Comment by taooceros** [comment]
fk I shouldn't reformat. I will revert back

**Review by jjw24 — APPROVED** [review]

**Comment by onesounds** [comment]
> Look good but clock in Metro Server theme still uses the old style. Is this intended?

Intended. I made theme can adjust clock layout.
Detail Theme style will adjust in other pr.

**Pull request merged**
