### PR TITLE
Improve context menu results

### PR DESCRIPTION
**Pull request by Garulf**
## Concern

`Result` should be responsible for how it's deep copied and not the context menu method.

## Solution

Move all deep copy logic into `Result`

### CODE REVIEW

**Comment by VictoriousRaptor** [comment]
build failed?

**Comment by Garulf** [comment]
I think a test may have failed because i changed `Result`

**Comment by taooceros** [comment]
We actually only need a shalow copy of the result. Do we get any library that can do that?

**Comment by taooceros** [comment]
@Garulf want to get this into 1.18? I think it's pretty nice to have.

**Comment by Garulf** [comment]
> @Garulf want to get this into 1.18? I think it's pretty nice to have.

Sounds good to me!

**Review by taooceros — APPROVED** [review]

**Pull request merged**
