### PR TITLE
[Dev] Use path of lnk file when launching proram

### PR DESCRIPTION
**Pull request by VictoriousRaptor**
#1546 changed the behavior of launching .lnk programs. It directly launches the program pointed to. It wasn't intended. Got mislead by the varaible name.) which brings an issue. Start Menu shortcut of Discord can't be launched. This is because it acutally points to `blabla\Discord\Update.exe --processStart Discord.exe` and we don't parse the params. Fixed in this pr.

Known issue of program plugin (not related to this pr or 1546): can't distinguish different .lnk files pointing to the same target but with different params.

### CODE REVIEW

**Comment by jjw24** [comment]
>Known issue of program plugin (not related to this pr or 1546): can't distinguish different .lnk files pointing to the same target but with different params.

Could you please create an issue if not already done so.

**Review by jjw24 — APPROVED** [review]
👍

**Comment by VictoriousRaptor** [comment]
> > Known issue of program plugin (not related to this pr or 1546): can't distinguish different .lnk files pointing to the same target but with different params.
> 
> Could you please create an issue if not already done so.

Already working on it. I will push the fix later.

**Comment by jjw24** [comment]
Legend

**Pull request merged**
