### PR TITLE
stop trigger global hotkey when shell plugin is not enabled

### PR DESCRIPTION
**Pull request by taooceros**
temporary fix for #950 
We should stop init disabled plugin when startup. corresponding to idea of #391

### CODE REVIEW

**Comment by jjw24** [comment]
i thought disabled plugins are not loaded at all?

**Comment by jjw24** [comment]
any chance we can stop init disabled plugin when startup? this means they wont even show up in Settings window right?

**Comment by taooceros** [comment]
> any chance we can stop init disabled plugin when startup? this means they wont even show up in Settings window right?

Possible. Currently the Init method does two thing, passing context to the plugin, and allow it to do some initialization thing. If the plugin needs the initialization for setting panel, they may fail to create it without the initialization.

**Comment by jjw24** [comment]
Just checked out the rest of the code, i see your point, will merge this in for now.

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
