### PR TITLE
fix error message not working + increase delay

### PR DESCRIPTION
**Pull request by jjw24**
fix pm initialisation error message not working due to main window not initialised yet
image

ran into the init error message several times during debug sessions, so increase delay

### CODE REVIEW

**Comment by taooceros** [comment]
Maybe let's keep the delay, but move the error message to the continuation of updatemanifest task if fail.

**Comment by jjw24** [comment]
hmm, not exactly sure what you mean, maybe you can just update the PR branch with it

**Comment by taooceros** [comment]
> hmm, not exactly sure what you mean, maybe you can just update the PR branch with it

Yeah sure, will do it later.

**Comment by taooceros** [comment]
Done, please review the last commit. @jjw24

**Comment by jjw24** [comment]
i dont see a commit

**Comment by taooceros** [comment]
> i dont see a commit

Sorry, forget to push😅🤣

**Comment by taooceros** [comment]
Is the last commit good? If that seems good, I will approve.

**Comment by jjw24** [comment]
good to go now, you can approve and merge

**Review by taooceros — APPROVED** [review]
Thank you!

**Pull request merged**
