### PR TITLE
Add "hh:mm:ss tt" to clock formats.

### PR DESCRIPTION
**Pull request by z1nc0r3**
#1678 Added hh:mm:ss tt to the clock formats to show seconds in the clock.

### CODE REVIEW

**Review by jjw24 — COMMENTED** [review]
Hi there, thanks for the pr.

As @onesounds mentioned, there maybe a slight impact on memory, could you please test how much impact there will be. This can be showing a screenshot of before and after using this format.

We will also make it clear to users that this may impact memory. @onesounds what's the best way to do this? Tooltip or warnin text etc?

**Review by jjw24 — CHANGES_REQUESTED** [review]
See comments please.

**Comment by onesounds** [comment]
I'll test and then if there are lot memory using, I'll add description part.(aka tooltip)

**Comment by onesounds** [comment]
I have confirmed that resource usage does not increase in particular.
I think it would be okay not to add an explanation.

**Review by VictoriousRaptor — APPROVED** [review]

**Comment by jjw24** [comment]
Haven't had a chance to take a look, will do so soon

**Review by z1nc0r3 — COMMENTED** [review]
`hh:mm:ss tt` and `HH:mm:ss tt` are not the same.

**Comment by VictoriousRaptor** [comment]
> `hh:mm:ss tt` and `HH:mm:ss tt` are not the same.

I know, but tt in `HH:mm:ss tt` is redundant.

**Pull request merged**
