### PR TITLE
Fix empty query

### PR DESCRIPTION
**Pull request by onesounds**
for Fix the https://github.com/Flow-Launcher/Flow.Launcher/discussions/735 issue.

**Why it happen.**
- There is no problem with the logic. Just WPF UI thread is not updated first.
- https://social.msdn.microsoft.com/Forums/en-US/e974c849-90ea-4741-9a27-0ae4857bc3c2/wpf-update-ui-in-while-window-is-hidden?forum=wpf
- https://stackoverflow.com/questions/3367430/force-wpf-to-render-a-window-while-hidden

**so...**
1. force update using Dispatcher
https://stackoverflow.com/questions/1644079/change-wpf-controls-from-a-non-main-thread-using-dispatcher-invoke
It is too difficult for me.

2. Using Opacity?
- Visibility hidden or collapsed doesn't update data. Opacity 0 is possible.
- I thought opacity 0 will reserved area. 

**It is my solution**
1. When It close (there are two place, esc command and toggle window) 
2. update query data. (replace query data by setting)
3. window opacity = 0 (it just for hide delay. The user feels that the window closes quickly.)
4. 30ms delay (Time for update data. it's not showing because opacity 0)
5. close (hidden) window.

When I tested it, it worked well. feel so good.

**problem**
- I tested a number of things. I think opacity 0 doesn't reserved area. You can use this as a substitute for closing windows.
- but window visible using in everywhere. I can't change everything.
- If you close the progress bar when you see it, it remains the next time you open it.
- So tricky.

you guys will be able to trimmed more neatly.

### CODE REVIEW

**Comment by jjw24** [comment]
what do you mean visible/hidden case?

**Comment by onesounds** [comment]
> what do you mean visible/hidden case?

like 'open item' thing. In addition to esc and toggle hotkey, there are situations in which windows are closed.
I think closing should be a function and connected to everything.Flow uses the visibility code everywhere, but I haven't checked it all.

Anyway, looking at Power Toy, It was a similar way to me.
https://github.com/microsoft/PowerToys/commit/3a15276668289e77b264bf89e8b12264de89b108

I'll try copying it, but I don't know if it'll work out. If I success, I'll reopen.

**Comment by taooceros** [comment]
It's similar, just await 100ms before changing to collapse. They use Thread.Sleep(100), which I am not sure whether will cause a bit slow on closing.

**Comment by onesounds** [comment]
It was brought from powertoy to process toggle and updates. I think I fixed it. The opacity trick written above was also used.
Some codes are in the mainviewmodel.cs (when esc and choose item) and the rest are in the hotkeymapper. 
(alt+space toggle uses hotkeymapper) I think I have to transfer hotkeymapper classe them all, but it's too much for me.
I fixed what I saw first. It does not work when the plug-in context menu is selected. I don't know where to fix this.
I leave the rest to you guys.

**Comment by onesounds** [comment]
> Hm why all hotkey mapper method is moved to mainviewmodel? Previously #565 extract those method related to hotkey from mainviewmodel to hotkey mapper. I don't think we should move it back.
> 
> I can handle the rest of the refactor if you think sometimes you encounter trouble in using the method across classes.

I didn't see that issue discussion. I didn't know why this was separated. I just thought the empty query method should be separated from hotkey. I thought it was intuitive to be by the window. 

Anyway, I referred to Power Toy. They probably organized the code better than me. I focused on changing window hiding to a unified method. I just moved what was called together while moving the import empty query. If there seems to be a problem, you can correct it. As you know, I don't know how to structure it.

**Pull request merged**
