### PR TITLE
Optimize startup

### PR DESCRIPTION
**Pull request by taooceros**
A few enhancement I found during the investigation of #371

### CODE REVIEW

**Comment by taooceros** [comment]
Oops, let me fix the build fail.

**Comment by jjw24** [comment]
version bumps as well please

**Comment by jjw24** [comment]
@taooceros need to also bump bookmarks plugin version.

Does removing readonly improve anything?

I don't remember, remind me again what's the benefit of using enumerate over get for directories?

**Review by jjw24 — CHANGES_REQUESTED** [review]
See comments

**Comment by taooceros** [comment]
> @taooceros need to also bump bookmarks plugin version.
> 
> Does removing readonly improve anything?
> 
> I don't remember, remind me again what's the benefit of using enumerate over get for directories?

No, but readonly requires initialization in constructor, while we construct instance in sync. I move that to Init() to allow parallel initialization.

**Review by jjw24 — APPROVED** [review]

**Comment by taooceros** [comment]
＞ I don't remember, remind me again what's the benefit of using enumerate over get for directories?

I miss this question. It will be faster because we don't need to wait the enumeration finish to create an array and do action earlier.

**Pull request merged**
