### PR TITLE
Small Design Fix in Setting Window

### PR DESCRIPTION
**Pull request by onesounds**
1. https://github.com/Flow-Launcher/Flow.Launcher/issues/883 Change Wizard window to modal when open in about only
2. Change Label Width Size 
image

3. Change Checkbox Position
image

4. Add Tab Key description in page 3 in wizard window

### CODE REVIEW

**Comment by taooceros** [comment]
What about make the width auto?

**Comment by onesounds** [comment]
> What about make the width auto?

it's not easy. "auto" is made wrong grid so I should use grid layout (very annoying work!) and 
change window width to responsive. and it has some issue with custom title bar. (it need fixed width)
Anyway, I change it to responsive.

**Comment by taooceros** [comment]
> > What about make the width auto?
> 
> it's not easy. "auto" is made wrong grid so I should use grid layout (very annoying work!) and 
> change window width to responsive. and it has some issue with custom title bar. (it need fixed width)
> Anyway, I change it to responsive. 

LOL ok🤣.

**Comment by onesounds** [comment]
Remove Priority "Minimum number = 0"
-> negative number is possible.

**Comment by onesounds** [comment]
Fix Impossible set negative number in priority

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
