### PR TITLE
Update to square logo

### LINKED ISSUE #4: New logo for Flow Launcher

### PR DESCRIPTION
**Pull request by Kalaschnik**
Resolves #4

### CODE REVIEW

**Comment by jjw24** [comment]
LGTM. Shall we get this PR in? @Flow-Launcher/team 

image


image

**Comment by JohnTheGr8** [comment]
@jjw24 sure. Let's replace the old icon as part of this PR...

**Comment by jjw24** [comment]
what do we want to do with the error image?
image

**Comment by Kalaschnik** [comment]
> what do we want to do with the error image?
> image

How about?
image

**Pull request closed without merging**
