### PR TITLE
Update issue template

### PR DESCRIPTION
**Pull request by jjw24**
Closing #2

### CODE REVIEW

**Comment by Kalaschnik** [comment]
I like when issues are splitted when you want to create one:

image

What do you folks think?

**Comment by SysC0mp** [comment]
I also think the template should be split up. Maybe we can directly switch to use the newer issue template workflow described [here](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates)

**Comment by jjw24** [comment]
That is a better idea actually, thanks guys. I will set it up later if no one else has.

**Comment by Kalaschnik** [comment]
You can delete the default one; here is mine (like in the screenshot) from a current project I’m working on:
https://github.com/Kalaschnik/tobii-eyetracking-utilities/tree/develop/.github/ISSUE_TEMPLATE

As of for the next 20 hours I’m busy. But I can merge your proposed changes into the splitted format if you like?

**Comment by jjw24** [comment]
> You can delete the default one; here is mine (like in the screenshot) from a current project I’m working on:
> https://github.com/Kalaschnik/tobii-eyetracking-utilities/tree/develop/.github/ISSUE_TEMPLATE
> 
> As of for the next 20 hours I’m busy. But I can merge your proposed changes into the splitted format if you like?

That would be sweet, thank you. I am away from comp for the next 8 hrs.

**Comment by Kalaschnik** [comment]
@jjw24 Done. See #97

**Comment by jjw24** [comment]
Closing in favour of https://github.com/Flow-Launcher/Flow.Launcher/pull/97

**Pull request closed without merging**
