### PR TITLE
JsonRPCPlugin Version 2

### PR DESCRIPTION
**Pull request by taooceros**

### CODE REVIEW

**Comment by jjw24** [comment]
why is this merging into the dotnet 6 branch instead? is this ready?

**Comment by taooceros** [comment]
> why is this merging into the dotnet 6 branch instead? is this ready?

Not really, but it works.

**Comment by jjw24** [comment]
should we change the base to Dev branch instead of dotnet 6?

**Comment by taooceros** [comment]
> should we change the base to Dev branch instead of dotnet 6?

well why not merge dotnet 6 before this one XD? I don't see a specific reason to not include dotnet 6 in 1.10

**Comment by jjw24** [comment]
Have you tested .net 5/core (if we still have any) with the Flow.Launcher.Plugin build?

**Comment by taooceros** [comment]
> Have you tested .net 5/core (if we still have any) plugins with the Flow.Launcher.Plugin build?

Yes, they will be separate.

**Comment by jjw24** [comment]
See #1353

**Pull request closed without merging**
