### PR TITLE
ignore null datetimes for pluginstoreitem

### PR DESCRIPTION
**Pull request by taooceros**
#2476 

Ignore any potential null value for struct (DateTime) which causes failed deserialization.

https://docs.microsoft.com/en-us/dotnet/api/System.Text.Json.Serialization.JsonIgnoreCondition?view=net-7.0
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/default-values

### CODE REVIEW

**Comment by VictoriousRaptor** [comment]
Do we still need this patch?

**Comment by taooceros** [comment]
Yes let's make it safe

**Comment by VictoriousRaptor** [comment]
TESTED? LGTM

**Review by VictoriousRaptor — APPROVED** [review]

**Comment by taooceros** [comment]
> TESTED? LGTM

nope but that's by document and it doesn't hurt to do that

**Pull request merged**
