### PR TITLE
Use CancellationToken to cancel Explorer index search task

### PR DESCRIPTION
**Pull request by taooceros**
Easy fix but compromised. I think it would be better if we can use full async instead of `GetAwaitor().GetResult`.
Link to #195 Explorer plugin cause threadpool task shortage.

#233 may allow this to become better if we don't need to create a new CancellationTokenSource but use the one in the main thread, and if we can make plugin use Task<Result> as result type, this can become even better that don't need to wait the result.

### CODE REVIEW

**Comment by jjw24** [comment]
hey @taooceros whats the issue this is fixing? and how do i repro it?

**Comment by jjw24** [comment]
> hey @taooceros whats the issue this is fixing? and how do i repro it?
all good i saw the comment in the othe PR:
image

**Comment by jjw24** [comment]
is this problem happening in dev?

**Comment by taooceros** [comment]
> is this problem happening in dev?

Not sure, but I believe it could happen.

**Comment by jjw24** [comment]
is this still needed now the async model is in?

**Comment by taooceros** [comment]
> is this still needed now the async model is in?

No, I will close this one.

**Pull request closed without merging**
