### PR TITLE
Add MessageBoxEx

### PR DESCRIPTION
**Pull request by onesounds**
## What's the PR

- Improve the MessageBox design.
- Dark mode is applied.

### CODE REVIEW

**Comment by jjw24** [comment]
Why is it called MessageBoxEx? what's 'Ex'?

**Comment by onesounds** [comment]
https://www.codeproject.com/Articles/5290638/Customizable-WPF-MessageBox

https://github.com/nmoschkin/MessageBoxEx

As an extension of the messagebox. the examples I saw used that name. I thought this was an ordinary name, but  I get the same question for the second time. why? Isn't this better to maintain the existing messagebox grammar? 

Here's the name I can think of. 
- messageBox2
- messageboxV2
- SuperSaiyanMessagebox
- CustomMessageBox
- mBox2
- messagebox64
- messageboxWii
- newSuperMessageBox
- iMessageBox
- messageBoxZero
- messageBoxModel2
- messageBoxExpansionPack
- messageBoxSeasonPass
- messageBoxZwei
...

**Comment by onesounds** [comment]
OK. Let me explain a little more.
1. The messagebox is not a customizable window. It is a window generated by WPF. So it's not affected by dark mode.
2. That's why people use the code under the name “MessageBoxEX”, keeping the syntax, but with their own design changes.
3. I'm not sure if it's possible to use this design and code while maintaining the “messagebox” syntax. In any case, the name needed to fit the existing syntax and be easily modifiable so that it would be easy to replace all the messagebox code in the entire code.

If you've ever used this window and checked for this issue (https://github.com/Flow-Launcher/Flow.Launcher/issues/881), you'll know why it's messageBoxEX. (taoo asked the same question. everyone too disinterested!!)

Anyway, I don't know if this code is usable or not. Someone should optimize it for me.

**Comment by jjw24** [comment]
I apologise, did not click in my head at the time that it is short for extension, and yes the points explained above are correct.

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
