### PR TITLE
Rename Docs folder to Artworks

### PR DESCRIPTION
**Pull request by jjw24**
Rename to more appropriate name, to store future artwork files

### CODE REVIEW

**Comment by Zeroto521** [comment]
I thought why not use [docsify](https://docsify.js.org/#/) to build a project called `Flow-Launcher/docs` or a directory called `Flow-Launcher/Flow. Launcher/docs` to center all docs.

**Comment by jjw24** [comment]
@Zeroto521 sounds like a good idea, did you want to set it up if I create a new repo?

**Comment by jjw24** [comment]
is it similar to [Sphinx](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjSjYam5-XuAhXKF3IKHSAFDZMQFjAAegQIBxAD&url=https%3A%2F%2Fwww.sphinx-doc.org%2F&usg=AOvVaw2RVBlhtQWJVcbws_C6-iax)?

**Comment by Zeroto521** [comment]
> is it similar to [Sphinx](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjSjYam5-XuAhXKF3IKHSAFDZMQFjAAegQIBxAD&url=https%3A%2F%2Fwww.sphinx-doc.org%2F&usg=AOvVaw2RVBlhtQWJVcbws_C6-iax)?

Sphinx is base on python, and docsify base on js.

docsify is more simple than sphinx.

> @Zeroto521 sounds like a good idea, did you want to set it up if I create a new repo?

Yeap, `Flow-Launcher/docs` would be fine.

We could write docs by markdown. And style let docsify do it.

**Comment by jjw24** [comment]
done @Zeroto521

**Comment by jjw24** [comment]
moved to https://github.com/Flow-Launcher/docs/pull/3

**Comment by jjw24** [comment]
this is just a straight folder rename, folder is just where we keep our graphic files.

**Review by taooceros — APPROVED** [review]

**Pull request merged**
