### PR TITLE
Add WinGet update CD

### LINKED ISSUE #463: Add WinGet repo update to CICD
New flow releases need to be updated in the WinGet repo, this should be done via Flow's CICD pipeline-AppVeyor file using WinGet update command

### PR DESCRIPTION
**Pull request by jjw24**
Publish new flow updates to WinGet repo and only on success build of master branch.

Tested on a branch only build and 1.8.0 update PR is already submitted to the WinGet repo

Close #463

### CODE REVIEW

**Comment by pc223** [comment]
> Currently DRAFT...nothing to see here...

Haha, the struggle of git commit msg is real 🤣 thought just me do this.

**Comment by jjw24** [comment]
Haha, there's not much documentation around this so, the struggle is, very real 🤣

**Comment by taooceros** [comment]
Should we hide those tokens from appvoyer.yml, which is public?

**Comment by JohnTheGr8** [comment]
> 
> 
> Should we hide those tokens from appvoyer.yml, which is public?

they're encrypted, don't worry ;)

**Comment by jjw24** [comment]
All good to go @JohnTheGr8 @taooceros ?

**Review by JohnTheGr8 — APPROVED** [review]

**Pull request merged**
