### PR TITLE
Scroll to selected item when expanded or size changed

### PR DESCRIPTION
**Pull request by taooceros**
When a plugin's settings is clicked on, it will automatically snap to the top to fill the entire settings window.

### CODE REVIEW

**Comment by jjw24** [comment]
@taooceros what's this one? Could you fill in the details please.

Remind me again what's the no-pr-activity label for?

**Comment by taooceros** [comment]
> @taooceros what's this one? Could you fill in the details please.
> 
> 
> 
> Remind me again what's the no-pr-activity label for?

It's like when you open a plugin setting, it will be moved to top so it is easier to check the setting. It will help user to configure settings that has larger height.

**Comment by taooceros** [comment]
I am not sure about the no pr activity. @Garulf could you share some insight about what that is for?

**Comment by Garulf** [comment]
> I am not sure about the no pr activity. @Garulf could you share some insight about what that is for? 

Instead of a stale label on PRs that haven't seen any updates for some time it uses that label. I was hoping it would just give us a heads up on any PRs that may need some TLC.

**Pull request merged**
