### PR TITLE
Update themes

### PR DESCRIPTION
**Pull request by lemonnuggets**
Added Nord and Nord Darker themes.

### CODE REVIEW

**Comment by lemonnuggets** [comment]
# Nord Darker
image
# Nord
image

**Comment by taooceros** [comment]
Seems great! Thank you! I would like to change some other themes before approving.

**Comment by taooceros** [comment]
## Gray
image
## White
image

**Comment by jjw24** [comment]
👍 👍 great stuff everyone

@taooceros i kinda like the opacity of BlurBlack so lets add your version as a darker theme

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
