### PR TITLE
Update url website in Settings

### PR DESCRIPTION
**Pull request by jjw24**
Update the website url in Settings' About tab

### CODE REVIEW

**Comment by JohnTheGr8** [comment]
@jjw24 let's also update the `Find more plugins` link. We could make it point to the manifest repo and have a (categorized) list of plugins in the readme, perhaps?

**Comment by jjw24** [comment]
> @jjw24 let's also update the `Find more plugins` link. We could make it point to the manifest repo and have a (categorized) list of plugins in the readme, perhaps?

good pickup.

>We could make it point to the manifest repo

hmm maybe instead just change the query to list the plugins? Ideally even load the plugins in the Settings page, this maybe something to come in the next iteration.

> have a (categorized) list of plugins in the readme, perhaps?

This means we also need to maintain the list in the readme right? Add a new plugin in the manifest json and then need to also add to the list in the readme.

Ideally users dont need to visit the repo and plugin devs only need to do so to add or update their plugin

**Comment by JohnTheGr8** [comment]
> hmm maybe instead just change the query to list the plugins? Ideally even load the plugins in the Settings page, this maybe something to come in the next iteration.

I dont know, people _would_ expect a link to open when they click on this. If the query window opened instead, it could be unexpected/awkward...

> This means we also need to maintain the list in the readme right? Add a new plugin in the manifest json and then need to also add to the list in the readme.

Not a big maintenance cost, is it? Plugin devs update the readme once in their first PR, just an extra line. This can include name, short description, link to source code and issue tracker.

> Ideally users dont need to visit the repo and plugin devs only need to do so to add or update their plugin

Having all plugins listed and organized somewhere would help, especially for potential users that are trying to decide if Flow is worth a try. But anyway, it's just an idea...

**Comment by jjw24** [comment]
> > hmm maybe instead just change the query to list the plugins? Ideally even load the plugins in the Settings page, this maybe something to come in the next iteration.
> 
> I dont know, people _would_ expect a link to open when they click on this. If the query window opened instead, it could be unexpected/awkward...
> 

yeah true. What about just removing it and implement a category system when more plugins are submitted? When we got more plugins we can use the category system when loading in Setting. 

> > This means we also need to maintain the list in the readme right? Add a new plugin in the manifest json and then need to also add to the list in the readme.
> 
> Not a big maintenance cost, is it? Plugin devs update the readme once in their first PR, just an extra line. This can include name, short description, link to source code and issue tracker.
> 
> > Ideally users dont need to visit the repo and plugin devs only need to do so to add or update their plugin
> 
> Having all plugins listed and organized somewhere would help, especially for potential users that are trying to decide if Flow is worth a try. But anyway, it's just an idea...

**Comment by jjw24** [comment]
Updated the url. Please re-review

**Review by JohnTheGr8 — APPROVED** [review]

**Pull request merged**
