### PR TITLE
move ISavable to Flow.Launcher.Plugin\Interfaces

### PR DESCRIPTION
**Pull request by taooceros**
TODO: an async version for this interface?

### CODE REVIEW

**Comment by jjw24** [comment]
do we need async for this? this is just writing json files

**Comment by taooceros** [comment]
I am not sure. I think it should be fast, and this is only called when `exit`. Have you encountered any stunt when exiting?

**Comment by jjw24** [comment]
Yeah seems fast for me also, no issues

**Comment by taooceros** [comment]
> Yeah seems fast for me also, no issues

Ok, so let's put that away until further needs.

**Comment by taooceros** [comment]
@jjw24 So is this ok to be merged?

**Comment by jjw24** [comment]
Yes, approved, lets hold off merging until 1.8.0

**Comment by taooceros** [comment]
> Yes, approved, lets hold off merging until 1.8.0

Oh yeah, agree with you

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
