### PR TITLE
Finishes Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by GuiArcencio**
Hi! I noticed that some parts of the PT-BR (my native language) translation were incomplete, inconsistent or simply untranslated. I added the missing translations and fixed a few inconsistencies, semantic errors and typos.

### CODE REVIEW

**Comment by taooceros** [comment]
Hi, thanks for the contribution! However, all of our translation process are now converted to crowdin. We are not able to accept any github pr regarding localization as that won't be synchronized to crowdin and will be reverted if we merge pr from crowdin. Would you mind porting all this change to crowdin so we can align everything?

**Comment by jjw24** [comment]
Hi there, please head over to https://crowdin.com/project/flow-launcher and apply these translation changes.

Closing this PR.

**Comment by jjw24** [comment]
@taooceros should be possible to add a comment to the top of en.xaml to tell people to head over to Crowdin instead of changing the xaml files.

**Comment by taooceros** [comment]
> @taooceros should be possible to add a comment to the top of en.xaml to tell people to head over to Crowdin instead of changing the xaml files.

Sounds good

**Pull request closed without merging**
