### PR TITLE
Caret position fix : Include PR #1074

### LINKED ISSUE #1025: Shell plugin "WIN+R" hotkey cursor default position error
use WIN+R hotkey launch input box, default curosr position is at the front. 
If you want to run the command, you need to move the cursor to after the ">" character
image

### LINKED ISSUE #1070: Custom Query Hotkey feature not usable because of incorrect caret position
**Describe the bug/issue**

Maybe I'm the only user wanting to use this feature. The Custom Query Hotkey feature is not usable because the caret position is at the beginning of the query at index 0. At the end of the query should be a space and after that space is the supposed caret position.

**To Reproduce**

1. Assign 'b' as 'Action Keyword' for the 'Browser Bookmarks' plugin.
2. Create a Custom Query Hotkey with 'b ' as query.
3. Press the hotkey, caret is at pos 0 instead of pos 2.

**Screenshots**

Screenshot (18)

Screenshot (19)

**Your System**
```
(It's Windows 11)
Microsoft Windows [Version 10.0.22000.493]
Flow Launcher version: 1.9.3
```

### LINKED ISSUE #1078: The cursor position is at the start of the field instead of the end of the field after a call to Context.API.ChangeQuery("...") from inside a plugin
**Describe the bug/issue**
I'm developing a plugin (which target both Flow Launcher and Wox using an abstraction layer for both).

At a certain point in parsing the command, I decide to rewrite the current query from "vol +" to "vol change +".
To do that I use PluginInitContext.API.ChangeQuery("vol change +")

(Note: I happen to use the same API for both Wox and Flow Launcher)

**Expected result**:
- The new query is "vol change +" and the cursor is at the end of the query so any new char typed is inserted at the end of the string

**Actual result**:
- The new query is "vol change +" but the cursor is at the start of the query so any new char typed is inserted at the start of the string

**Notes**:

- Under Wox, the cursor is at the end of the query as excepteded.
- While the context is different, the problem may be related to #1070 and/or #1025 
- This context may help in solving the problem of the above issues
- I haven't yet looked at Flow Launcher source code about this problem

**Your System**:
```
Microsoft Windows [version 10.0.19043.1586]
Flow Launcher version: 1.9.3
```

**Flow Launcher Error Log**:
No log is generated during this sequence.

### PR DESCRIPTION
**Pull request by gissehel**
I include the PR #1074 because they both tried to address the same problem. I don't know if there are cases where #1074 applies or not, but it's more robust code, thus better.

Reason for this PR are explained in various comments of #1074

Should close #1025 close #1070 and close #1078

### CODE REVIEW

**Comment by taooceros** [comment]
Thank you! It's a very thoughtful debugging process, and the explanation is very valuable!
I will take a test now.

**Comment by taooceros** [comment]
I encounter a slightly delay when using low priority dispatching option, but I think it's not significant in release version.

**Comment by jjw24** [comment]
These changes are all tested and ready to roll?

**Comment by taooceros** [comment]
> These changes are all tested and ready to roll?

I think it is ok to roll. There's nothing bugs here, but only a small tradeoff to reduce the priority. Probably in the future we can adjust the event better.

**Comment by jjw24** [comment]
Make a new issue for this?

**Comment by taooceros** [comment]
> Make a new issue for this?

It's not really a serious bug and I have no clues whether it can be addressed.

**Comment by jjw24** [comment]
Yeah ok, I haven't started testing the new changes in Dev yet but will keep an eye out.

**Pull request merged**
