### PR TITLE
Fix calculator copy error

### PR DESCRIPTION
**Pull request by jjw24**
Re-PRed from https://github.com/Flow-Launcher/Flow.Launcher/pull/181. Authored by @taooceros

image

### CODE REVIEW

**Comment by jjw24** [comment]
image

**Comment by jjw24** [comment]
@taooceros Thanks for the fix :)

**Comment by jjw24** [comment]
Approved.

**Comment by jjw24** [comment]
This [post](https://stackoverflow.com/questions/44538513/clipboard-settext-fails-whereas-setdataobject-does-not) from SO sheds some light into this error

**Comment by taooceros** [comment]
> This post from SO sheds some light into this error

Yes, I have seen that post when trying to fix this, although this error is still feeling weird hhhh.😅

**Pull request merged**
