### PR TITLE
Fix EmptyQueryMode when opened context menu

### LINKED ISSUE #2019: BUG: "Empty last query" does not reset the context menu
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Context menu from previous query will still be active despite "Last query style" set to "Empty last query".

### To Reproduce

1. Set "Last query style" to "empty last query" (and "Hide Flow Launcher when focus is lost" to true)
2. Enter query and open context menu for a result item
3. Blur focus for launcher (launcher hides at this point)
4. Reactivate flow launcher. Context menu from previous query will still be active

### Screenshots

image
image

### Flow Launcher Version

1.14.0

### Windows Build Number

22621.1413

### Error Log

Not an error

### PR DESCRIPTION
**Pull request by onesounds**
## What's The PR
- Resolve #2019 
- Fixes an issue where if you toggle flow while the context menu is open, the context menu is open when you reopen it.

### CODE REVIEW

**Comment by taooceros** [comment]
> looks like duplicate of #1024

not really duplicate since this pr only reset when use the empty mode.

**Comment by jjw24** [comment]
Getting this error when I use empty last query

image


Please also include in tests other query mode functions still work as expected.

**Comment by onesounds** [comment]
I'm running out of time, so I change it to Draft for now. I'll check it when I have time.

**Comment by jjw24** [comment]
This fix is covered by PR 1024

**Pull request closed without merging**
