### PR TITLE
Implement Async Result Execution

### PR DESCRIPTION
**Pull request by taooceros**
Result Execution can take quite long (Especially for JsonRPCPlugin), which cannot handle threadpool easily (requiring subprocess to prevent long execution time).

### CODE REVIEW

**Comment by taooceros** [comment]
@Flow-Launcher/team Is ActionAsync named better or AsyncAction named better🤔?

**Comment by jjw24** [comment]
AsyncAction

**Review by jjw24 — APPROVED** [review]

**Comment by taooceros** [comment]
@jjw24 I couldn't reproduce the issue you said earlier, and I take a look on the code, only possible issue is that `RequestAsync` will throw an error when response is empty, but I remember I have suppressed it earlier. Could you share a more detailed reproduction process?

**Comment by jjw24** [comment]
Able to replicate with BrowserHistory plugin, as soon as you open one of its results.

**Pull request merged**
