### PR TITLE
Add github dependency bot

### PR DESCRIPTION
**Pull request by taooceros**
Add automatic check for dependency update

### CODE REVIEW

**Comment by jjw24** [comment]
Upping the versions will require testing, would it not be better to test while you are choosing to upgrade the version? 

This will create a lot of noise in the pr section

**Comment by taooceros** [comment]
> Upping the versions will require testing, would it not be better to test while you are choosing to upgrade the version?
> 
> This will create a lot of noise in the pr section

We can make that check weekly/monthly, which means it will only create a version update pr once a week/month. In most situation, we don't update version because we are lazy to update hhh🤣.

**Comment by jjw24** [comment]
Isn't this going to run through and create or for every version upgrade? This is going to create a fair bit prs.

Again you have to test to do the upgrade, which I would prefer effort put into enhancements instead and upgrade the required packages if needed

**Comment by taooceros** [comment]
> Isn't this going to run through and create a pr for every version upgrade? This is going to create a fair bit prs.

I don't think so. It shall create one pr once a week for all update if it has detected an update. 

> Again you have to test to do the upgrade, which I would prefer effort put into enhancements instead and upgrade the required packages if needed

Unless there's a breaking change (like squirrel), I don't think updating the a dependency will require a lot of testing.

**Comment by jjw24** [comment]
We have a lot of old packages, it's going to upgrade a lot of them.

Can you check how many updates it will create for please

**Comment by taooceros** [comment]
I will take a try in my fork first.

**Comment by taooceros** [comment]
image
It will behave like this. Each update with an pull request, and it will list the release note and commit difference for each update.

**Comment by jjw24** [comment]
only 5 packages need updating?

**Comment by taooceros** [comment]
> only 5 packages need updating?

No, it is because we can limit the count of pr created one time (which is 5)

**Comment by jjw24** [comment]
Would it be better to make an individual branch, upgrade all the non-breaking upgrades on in this branch and test it out before applying the bot?

**Comment by taooceros** [comment]
> Would it be better before applying the bot to make an individual branch, upgrade all the non-breaking upgrades on this branch, test them out and merge into dev first?

Sounds reasonable

**Comment by taooceros** [comment]
@jjw24 shall we merge the dependabot?

**Comment by jjw24** [comment]
We have a lot of prs in the pipeline atm, will this change add a lot more? If so can we bump all NuGet packages on a seperate branch, test everything ok and merge in before merging this one so we start with a good baseline.

**Comment by Garulf** [comment]
You can limit the maximum PR's dependabot is able to create with: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit

**Comment by taooceros** [comment]
> You can limit the maximum PR's dependabot is able to create with: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit

the default is 5, which I think is quite reasonable

**Comment by Garulf** [comment]
Seems reasonable to me. Our tests will still run on each PR so in theory we get updated packages for free.

**Comment by jjw24** [comment]
Ok let's merge this after 1.9.5

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
