### PR TITLE
Add a MemoryStream buffer to ReadStream first

### LINKED ISSUE #598: Python plugin: Flow Launcher hangs on stream output larger than buffer
**Describe the bug/issue**

**To Reproduce**
1. Any python plugin that returns more then 5 results causes FLow Launcher to never return results
2. Flow Launcher stays in infinite loading state

**Your System**
```
Windows build number: Microsoft Windows [Version 10.0.22000.100]
Flow Launcher version: 1.8.0
```
**Flow Launcher Error Log**
No error is ever logged

### PR DESCRIPTION
**Pull request by taooceros**
fix #598

### CODE REVIEW

**Comment by taooceros** [comment]
@Garulf https://ci.appveyor.com/api/buildjobs/ylh2uokiws4ee2hw/artifacts/Output%2FPackages%2FFlow-Launcher-v1.8.0.exe

**Comment by jjw24** [comment]
@taooceros could you let me know what's tested please

**Comment by taooceros** [comment]
> @taooceros could you let me know what's tested please

I have tested the scenario descripted in #598 (a very large json output). It works fine with very large json (1500000 items).

The change is really simple. I just add a memorystream layer to read the console output from the process allowing it to exit, which causes the hang.

**Comment by Garulf** [comment]
Testing in a moment, thank you so much for looking into this!

**Comment by Garulf** [comment]
@taooceros Works perfectly! All values are being returned and Flow Launcher no longer gets stuck in a loading state.

**Comment by taooceros** [comment]
> @taooceros Works perfectly! All values are being returned and Flow Launcher no longer gets stuck in a loading state.

Perfect! Thank you so much for reporting the bug!

**Comment by Garulf** [comment]
Not sure whats causing this error but it might be releated:
```
03:09:09.2594-04:00 - ERROR - JsonRPCPlugin.ExecuteAsync - Exception for filename <C:\Users\William\AppData\Local\Programs\Python\Python39\pythonw.exe> with argument <>
EXCEPTION OCCURS: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at async Task System.IO.Stream.CopyToAsyncInternal(Stream destination, int bufferSize, CancellationToken cancellationToken)
   at async Task<Stream> Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) x 2 in C:/projects/flow-launcher/Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs:line 288
```

**Comment by taooceros** [comment]
This exception shouldn't be logged. Weird. Will take a look later.

**Comment by jjw24** [comment]
@taooceros let me know when this is ready, assuming you are still looking into the log above.

**Comment by taooceros** [comment]
@jjw24 Good to review. I add another manual `process.kill()` to kill the process once the token is expired.

**Comment by taooceros** [comment]
Hold on, I found an issue, let me fix it.

**Comment by taooceros** [comment]
Done

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
