### PR TITLE
Support Application Uri in OpenUrl API call

### PR DESCRIPTION
**Pull request by taooceros**
Fallback to direct process open when uri is not started with http/https

### CODE REVIEW

**Comment by JohnTheGr8** [comment]
Maybe add a different overload that accepts a `Uri` for such cases? Having the `inPrivate` parameter there when this might not run in browser is awkward.

**Comment by taooceros** [comment]
> Maybe add a different overload that accepts a `Uri` for such cases? Having the `inPrivate` parameter there when this might not run in browser is awkward.

Hm if that's the case, I would doubt whether we should include a new public api because it is simply a helper function.

**Comment by JohnTheGr8** [comment]
> 
> Hm if that's the case, I would doubt whether we should include a new public api because it is simply a helper function.

nothing about this suggests that you can pass an application Uri and it will be started as a process:

https://github.com/Flow-Launcher/Flow.Launcher/blob/b64dd27d5310d196adfe81cb18c10e76ed8bde8f/Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs#L230-L233

**Review by jjw24 — CHANGES_REQUESTED** [review]
please update

**Comment by jjw24** [comment]
> > Hm if that's the case, I would doubt whether we should include a new public api because it is simply a helper function.
> 
> nothing about this suggests that you can pass an application Uri and it will be started as a process:
> 
> https://github.com/Flow-Launcher/Flow.Launcher/blob/b64dd27d5310d196adfe81cb18c10e76ed8bde8f/Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs#L230-L233

resolved.

**Review by jjw24 — APPROVED** [review]

**Comment by jjw24** [comment]
@taooceros i dont think the logic prior to my change is correct. Can you give me an App URI example you were testing with.

**Comment by jjw24** [comment]
@taooceros sorry, my mistake. This is now fixed in PR1002

**Pull request merged**
