### PR TITLE
Fix spellings in translation keys

### PR DESCRIPTION
**Pull request by tech189**
Small fix to spellings I noticed while trying out this program!

- "upadte" --> "update"
- "Windows Setting" --> "Windows Settings"

### CODE REVIEW

**Comment by taooceros** [comment]
Thanks for the patch! We may also need to update the reference to the key since you have changed the key name.

**Comment by tech189** [comment]
Okay! Is that some file I can modify in my PR or something in the translation site I don't have access to?

**Comment by taooceros** [comment]
> Okay! Is that some file I can modify in my PR or something in the translation site I don't have access to?

It should be within the code. Possible some dynamic resource in xaml and some call to api.GetTranslation(). They are called via key, so you may need to search with original key.

**Comment by tech189** [comment]
I couldn't find any more occurences of 'upadte' in this repository. All the language xaml files have been modified in the PR. It seems the keys I modified are not actually used yet in the project (or maybe they used to?). Compare with my modification of the content of `RecommendBluetoothDesc` which is used in https://github.com/Flow-Launcher/Flow.Launcher/blob/132100512f1bbefeb71fb6a0079439d226639ccc/Flow.Launcher/Resources/Pages/WelcomePage4.xaml and is referred to by `Text="{DynamicResource RecommendBluetoothDesc}"`

**Comment by tech189** [comment]
No worries, even if the other keys are not needed, having good spelling for the Welcome Page would be nice!

**Comment by JohnTheGr8** [comment]
Let's also get rid of [Plugins/Flow.Launcher.Plugin.ControlPanel/Languages/ko.xaml](https://github.com/Flow-Launcher/Flow.Launcher/blob/dev/Plugins/Flow.Launcher.Plugin.ControlPanel/Languages/ko.xaml) as part of this, yeah?

**Comment by jjw24** [comment]
@tech189 just to give some context, the [plugin](https://github.com/Flow-Launcher/Flow.Launcher/blob/dev/Plugins/Flow.Launcher.Plugin.ControlPanel) is no longer used anymore, so can just delete that entire Flow.Launcher.Plugin.ControlPanel folder.

**Comment by tech189** [comment]
I noticed some more spellings I hope they are okay to add to this PR! 😅

**Comment by jjw24** [comment]
Of course, go for it.

**Review by jjw24 — APPROVED** [review]
LGTM. I just bumped WebSearch plugin so this PR also patches it up.

**Pull request merged**
