### PR TITLE
Fix thumbnail image loading

### PR DESCRIPTION
**Pull request by SysC0mp**
Should fix the missing thumbnail images.
ImageLoader class is not thread-safe at it's current state and the icons cannot be loaded in parallel.

### CODE REVIEW

**Comment by JohnTheGr8** [comment]
lgtm

**Comment by theClueless** [comment]
@SysC0mp what can happen if it is run in parallel? what is not thread safe? I agree that it can load some images more than once but the amount of time it will invest in doing it serially seems worse to me.

**Comment by jjw24** [comment]
I have the same concern as @theClueless. Might need to investigate a bit more to see if there is an improved solution, otherwise it might take longer to load if user has a lot of images.

**Comment by jjw24** [comment]
@SysC0mp could you share the error in the logs for those images not loaded please.

**Comment by SysC0mp** [comment]
Following error is thrown for a couple of thumbnails on Flow startup: 
image
image
The images which throw that always differ. But I am curious because those errors should occur on your machines too directly when you start Flow using the Debug config from the dev branch. 

Call stack: 
image

**Comment by JohnTheGr8** [comment]
Was just testing this @SysC0mp and I am getting this error as well. The error goes away for me if I set `ThumbnailOptions` to `ThumbnailOnly`.

I'll make a suggestion commit now so you can check it out yourself.

**Comment by JohnTheGr8** [comment]
@SysC0mp committed, give it a try

**Comment by SysC0mp** [comment]
Thanks for testing @JohnTheGr8 but unfortunately I still get the errors with that option provided.

**Comment by JohnTheGr8** [comment]
Well I just tried again and got the error myself, what the hell. I tried a few times before and the change to `ThumbnailOptions` did the trick, but now it fails again. 
Sorry for wasting your time.

**Comment by SysC0mp** [comment]
All good, any testing & help is appreciated 👍  Maybe we could try to add some kind of "retry" logic to it because it seems that this error occurs only the first time trying for some of the thumbnails. I'll give that a try.

**Comment by SysC0mp** [comment]
I changed the image loading back to parallel and added a retry logic to the whole `LoadInternal` method. In that way, the error is fixed for me and we do not need to sequentially load the thumbnails.

**Pull request merged**
