### PR TITLE
Release 1.9.4

### PR DESCRIPTION
**Pull request by jjw24**
Release Notes
=========

## Bug fixes
- Bumped NuGet.CommandLine from 5.4.0 to 5.7.2 #1241

- Fixed shell cmd command when used with quotes and spaces #1205

- Fixed occasional NullReferenceException error #1204

- Updated Python download mirrors #1187

- Fixed font-anti-aliasing #1119

- Fixed decimal separator when used as part of the query #1108

- Fixed plugins inside settings window to expand correctly and fill the entire window when required #1098

- Updated Shell plugin's default setting for replacing Win R hotkey to off #1087

- Fixed incorrect button visibility in Explorer plugin's setting panel #1077

- Updated Explorer's path search to not use index by default when searching inside directories #1076

- Fixed a silent error thrown when Chromium bookmarks are loaded #1071 

- Fixed typos in context menu result's plugin title and WindowsSettings' name #1056

- Fixed the occasional error 'No process is associated with this object' #1005

### CODE REVIEW

**Comment by taooceros** [comment]
merge to master instead of dev?

**Comment by taooceros** [comment]
also should we involve the new translations?

**Comment by jjw24** [comment]
yep

**Comment by jjw24** [comment]
> also should we involve the new translations?

I tried, but got messy because of the huge number of files changed. So I think might have to have them go with 1.10.0 release instead.

**Comment by taooceros** [comment]
> > also should we involve the new translations?
> 
> I tried, but got messy because of the huge number of files changed. So I think might have to have them go with 1.10.0 release instead.

ok make senses

**Comment by taooceros** [comment]
The build has failed. 
image

**Comment by taooceros** [comment]
It's because this one has add the property for copy.
https://github.com/Flow-Launcher/Flow.Launcher/pull/1108

**Comment by jjw24** [comment]
Should be good now.

**Comment by taooceros** [comment]
> Should be good now.

maybe open another pr target to dev for that in case we forget.

**Review by taooceros — APPROVED** [review]

**Comment by jjw24** [comment]
I merged master back into dev (https://github.com/Flow-Launcher/Flow.Launcher/commit/fee3d1da90e9c0946418e758220c7be82e2a0eca) now, looks good, the change was kept https://github.com/Flow-Launcher/Flow.Launcher/blob/fee3d1da90e9c0946418e758220c7be82e2a0eca/Plugins/Flow.Launcher.Plugin.Calculator/Main.cs#L93

**Pull request merged**
