### PR TITLE
New Crowdin updates

### LINKED ISSUE #796: Crowdin integration

### PR DESCRIPTION
**Pull request by jjw24**
close #796

### CODE REVIEW

**Comment by taooceros** [comment]
why every commit triggers a workflow....

**Comment by taooceros** [comment]
@jjw24 I guess you may need to reset the integration again😂. It won't download translation if I just resync it.

**Comment by jjw24** [comment]
As in wild out the changes in this branch?

**Comment by jjw24** [comment]
If it's resetting the changes to this branch, you can do it as well by doing force push back to the initial commit.

**Comment by taooceros** [comment]
> If it's resetting the changes to this branch, you can do it as well by doing force push back to the initial commit.

I think the issue is I delete the "branch" in crowdin to force it to reindex the files. However, the sync process won't download the exist translated files, so all translation will be lost in this one. Probably I can upload the files. I will take a try.

**Comment by taooceros** [comment]
the issue is crowdin won't download the translation file back to its server. Probably that will only be done the first time setting up the integration.

**Comment by taooceros** [comment]
@jjw24 merge this?

**Comment by jjw24** [comment]
Is it all working?

**Comment by taooceros** [comment]
> Is it all working?

I think so. By the way, why is it force pushed a few days ago?

**Comment by jjw24** [comment]
If it's working then yeah merge it in.

It was force pushed because our appveyor clogged up with all these pending jobs on the commits, I figured I squashed them into one will cancel those commits. If no one else fixed the clogging in appveyor pipeline then I think it worked.

Plus also I don't want these 211 something commits into our code base when it could be just one, so yeah.

**Comment by taooceros** [comment]
Oh it is squashed. Then it should be good

**Review by taooceros — APPROVED** [review]

**Comment by taooceros** [comment]
Merge this? It is not even toward dev so shouldn't be issue.

**Comment by jjw24** [comment]
Yeah lets merge it, we can solve the ci fail in the target branch

**Pull request merged**
