### PR TITLE
Release 1.4.1

### PR DESCRIPTION
**Pull request by jjw24**
Release Notes
=========

## Bug fixes

- Fixed unauthorised access to directory causing Flow to quit loading Win32 apps altogether  #210

### CODE REVIEW

**Comment by JohnTheGr8** [comment]
@jjw24 why don't we go with #207 instead?

**Comment by taooceros** [comment]
> @jjw24 why don't we go with #207 instead?

I think @jjw24 wants to publish the large bug fix faster, since #207 will include more feature enhancement.

**Review by taooceros — APPROVED** [review]

**Comment by JohnTheGr8** [comment]
I see no reason not to release everything included in #207 if we're going to make a release...

**Review by JohnTheGr8 — CHANGES_REQUESTED** [review]
IMO we can release all changes from #207. No good reason to selectively pick these changes...

Disapproving this PR because merging it to master will cause a CI failure (as I have mentioned to @jjw24 before).

**Pull request closed without merging**
