### PR TITLE
Fix calculator copy error

### PR DESCRIPTION
**Pull request by taooceros**
This is a bug that has existed a long time, and it is a quite weird bug. [#1204](https://github.com/Wox-launcher/Wox/issues/1204)
I am not sure whether this has been solved, but in my computer, it did.

The solution is change Clipboard.SetText to Clipboard.SetDataObject.

### CODE REVIEW

**Comment by jjw24** [comment]
are you able to consistently repro the issue?

**Comment by taooceros** [comment]
Yes, in my computer, the error appears every time, even though the text has been copied.

**Comment by jjw24** [comment]
Change looks good.

Do you know why there are a list of commits even though it should just be one?

image

**Comment by taooceros** [comment]
> Change looks good.
> 
> Do you know why there are a list of commits even though it should just be one?
> 
> image
> 

That's because there are some other change in the dev branch of my fork so that I create this branch from master. I think those commit is the commit that has made toward the dev branch compare to the master branch.

**Comment by jjw24** [comment]
Sorry for being pedantic. Are you ok for me to re-pr this without those commits for you? Don't want to have you do it again

**Comment by taooceros** [comment]
Oh, that's fine. Thank you so much for doing it for me!

**Comment by jjw24** [comment]
> Oh, that's fine. Thank you so much for doing it for me!

done

**Comment by jjw24** [comment]
Before making a new change set I usually pull from Dev branch first to make sure I get the latest. Then I branch from Dev. 

Also a good tool I found with Git is GitKraken. Highly recommend it if you are working with public repos (private repos is a paid feature).

**Comment by moonxkang** [comment]
> This is a bug that has existed a long time, and it is a quite weird bug. [#1204](https://github.com/Wox-launcher/Wox/issues/1204)
> I am not sure whether this has been solved, but in my computer, it did.
> 
> The solution is change Clipboard.SetText to Clipboard.SetDataObject.

@taooceros 
Curious where exactly I go to change the Clipboard.SetText to Clipboard.SetDataObject. I am having this issue and while the text is copied to my clipboard it brings up the error message which closes out Wox. I'd like to resolve it so that error message does not appear again. 

Thanks!

**Comment by taooceros** [comment]
> > This is a bug that has existed a long time, and it is a quite weird bug. [#1204](https://github.com/Wox-launcher/Wox/issues/1204)
> > I am not sure whether this has been solved, but in my computer, it did.
> > 
> > The solution is change Clipboard.SetText to Clipboard.SetDataObject.
> 
> @taooceros 
> Curious where exactly I go to change the Clipboard.SetText to Clipboard.SetDataObject. I am having this issue and while the text is copied to my clipboard it brings up the error message which closes out Wox. I'd like to resolve it so that error message does not appear again. 
> 
> Thanks!

Are you encountering this issue for calculator plugin? If that's the case, you can follow how I change that in this PR. For other case, I may need a little bit more information to help you, or you can take a global search for Clipboard.SetText and change that.

**Comment by jjw24** [comment]
> > This is a bug that has existed a long time, and it is a quite weird bug. [#1204](https://github.com/Wox-launcher/Wox/issues/1204)
> > I am not sure whether this has been solved, but in my computer, it did.
> > The solution is change Clipboard.SetText to Clipboard.SetDataObject.
> 
> @taooceros
> Curious where exactly I go to change the Clipboard.SetText to Clipboard.SetDataObject. I am having this issue and while the text is copied to my clipboard it brings up the error message which closes out Wox. I'd like to resolve it so that error message does not appear again.
> 
> Thanks!

Does this error happen with with Flow also?

**Comment by moonxkang** [comment]
@taooceros this happens with pretty much anything I click on to copy to my clipboard but I use it mostly for calculations, so yes, the calculator plugin. Sorry for my ignorance here but what is PR?

**Comment by taooceros** [comment]
> @taooceros this happens with pretty much anything I click on to copy to my clipboard but I use it mostly for calculations, so yes, the calculator plugin. Sorry for my ignorance here but what is PR?
> 
> Sorry, I just realized this is for the FLOW LAUNCHER not Wox :( I am using Wox and encountering this issue.
> dam.

Haha no problem. Why not take a try on Flow? It has introduced quite a lot improvement beyond Wox, and I have fixed most of the copy issue in flow.

**Comment by moonxkang** [comment]
@taooceros yea i just discovered flow like a minute ago so I will give it a try lol. I use wox for calculations all the time so the copying issue has been a major issue for me. very disruptive to workflow.

**Comment by taooceros** [comment]
> @taooceros yea i just discovered flow like a minute ago so I will give it a try lol. I use wox for calculations all the time so the copying issue has been a major issue for me. very disruptive to workflow.

Yeah that's bug also distupt me a lot when I was using wox before.

**Comment by moonxkang** [comment]
if that issue is gone on Flow launcher, I'm already sold. ill give it a try. thank you!

**Comment by jjw24** [comment]
@moonxkang how you go?

**Comment by moonxkang** [comment]
@jjw24 just installed it. 100x easier to get it all set up. works like a charm. even added the dictionary plugin which took me like 5 tries on Wox. This had a simple toggle for "English translation" so was super simple. i also didn't need to install EVERYTHING along with Wox which was nice. super super glad I found this thread. thank you!

**Pull request closed without merging**
