### PR TITLE
change the default theme for fresh install

### PR DESCRIPTION
**Pull request by jjw24**
with the new modern ui coming, time to refresh the default theme used in the new install

let me know if there is another theme you feel more appropriate @Flow-Launcher/team

### CODE REVIEW

**Review by onesounds — DISMISSED** [review]

**Review by Garulf — DISMISSED** [review]
😎

**Comment by Garulf** [comment]
I think going forward @onesounds's. Win11light theme is very appropriate.

**Comment by Zeroto521** [comment]
Are there any pictures about this new theme?

**Comment by jjw24** [comment]
Current:
image

Proposed:
image

**Comment by Zeroto521** [comment]
An idea about light and dark themes.
What if they could automated switch based on system light and dark mode?

**Comment by jjw24** [comment]
Yeah that'd be nice, for think the library we r using offers this maybe.

Seems like you all cool with this, can some one approve this lol

**Comment by onesounds** [comment]
Both Dark and Light versions are included in dev.
Dark mode (base OS setting) is on the Plan, and related codes were also investigated. It is not difficult, but it is planned to be done later due to its large workload and low priority. It is difficult at 1.9.

**Review by Garulf — APPROVED** [review]

**Pull request merged**
