### PR TITLE
Plugin store

### PR DESCRIPTION
**Pull request by onesounds**
- Redesign Plugin page layout
- Added Plugin Store page
- Redesigned Plugin Priority Window pop out
- Updated setting window's label wording
- Removed auto hiding of scrollbar in setting window

### CODE REVIEW

**Comment by onesounds** [comment]
**Todo**
- [ ]  organize and placing version / init and query time / Action Keyword
- [ ]  Adjust Plugin's margin
- [ ]  If there's no setting page, hide separator
- [ ]  Add Page Title 
- [ ] Change Expander toggle button design (Remove Circle)
- [ ] Change to button. Priority / plugin folder / Action Keyword
- [ ] Responsive sidebar width 

**Check if it's possible**
- [ ] Change priority control to Number box
- [ ] Expand/collapse animation
- [ ] Smooth Scroll 
- [ ] Control styling in plugin setting

It would be nice if each plug-in had an example query description. (it's not plugin description)

**Comment by onesounds** [comment]
image

image

- I think install button need 3 state.  'install / installing... / update'.
- Uninstall is managed on the plug-in page.
- Check that the version has changed during refresh, and if there is anything to update, order it to the top (and add little green icon)

**Comment by taooceros** [comment]
I add a ShowWindow api for IPublicAPI. I think it is reasonable for plugin to have the ability to show up the mainwindow.

**Comment by jjw24** [comment]
we need a notification to indicate that the store is refreshing when clickded on the refresh button.

**Comment by jjw24** [comment]
i dont see any animation of refreshing though, which image is this?

**Comment by Garulf** [comment]
Working on a few alterations to the english translation

**Comment by jjw24** [comment]
Mouse wheel is not working? Is it working for the general section?

**Comment by taooceros** [comment]
> Mouse wheel is not working? Is it working for the general section?

Yeah I can reproduce. I remember I have seen an issue in stackoverflow talking about scrollviewer and listbox coexist may cause some issue.

**Comment by taooceros** [comment]
@jjw24 I fix that issue. It is because we have enable deferred scroll in the listbox. Just remove it will be fine.

**Pull request merged**
