### PR TITLE
Fix Error of loading backup when original file doesn't exists

### LINKED ISSUE #1853: Settings save error with v1.12.1
[2023-01-27.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10515208/2023-01-27.txt)

Flow Launcher version: 1.12.1
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\K OMM\AppData\Local\Programs\Python\Python311\python.exe
Node Path: 
Date: 01/27/2023 08:45:31
Exception:
System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.FileSystem.ReplaceFile(String sourceFullPath, String destFullPath, String destBackupFullPath, Boolean ignoreMetadataErrors)
   at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName, Boolean ignoreMetadataErrors)
   at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName)
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.TryLoadBackup() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 80
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.Load() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 52
   at Flow.Launcher.ViewModel.SettingWindowViewModel..ctor(Updater updater, IPortable portable) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 39
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 63
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 52
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### PR DESCRIPTION
**Pull request by taooceros**
fix #1853 

Note:
- It's too late for me to create a comprehensive test, but I believe it shall work. If anyone would like to give it a test, thank you so much!

### CODE REVIEW

**Comment by jjw24** [comment]
@taooceros how do I repro the error?

**Comment by taooceros** [comment]
> @taooceros how do I repro the error?

It is pretty weird that only happens when the original file doesn't exists but the backup exists.

**Comment by jjw24** [comment]
@taooceros what's a scenario where original file doesn't exists but the backup exists.

**Comment by taooceros** [comment]
> @taooceros what's a scenario where original file doesn't exists but the backup exists?
> 
> 

I can't think of one.

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
