### PR TITLE
Spanish & Spanish Latin America languages release for v1.9.5

### PR DESCRIPTION
**Pull request by jjw24**
These are all language files for Spanish & Spanish Latin America added to the dev branch at the time of this PR, copied across for v1.9.5 release.

I purposely left out the language files in Windows Settings plugin because the changes are too drastic.

Expected:
Should not have any differences in the language files between this branch and dev branch.

Tested:
Selected both Spanish and Spanish Latin America and observed that the language has changed on each screen including plugin settings.

### CODE REVIEW

**Comment by jjw24** [comment]
I am just playing it safe, I don't know how git will handle the differences there, this is just for a release so don't want to make it too complicated.

**Comment by taooceros** [comment]
Will it be hard to merge back? I am only concerning that.

**Comment by jjw24** [comment]
Yes my concern as well that's why I left the plugin alone, if you take a look I think there is already a default Spanish language file for master branch called 'es-EM', which is renamed (sort of) to 'es' in Dev.

**Comment by taooceros** [comment]
> Yes my concern as well that's why I left the plugin alone, if you take a look I think there is already a default Spanish language file for master branch called 'es-EM', which is renamed (sort of) to 'es' in Dev.

ok let's do that in the future. Hope it won't be too hard to merge back XD.

**Review by taooceros — APPROVED** [review]

**Comment by jjw24** [comment]
Shouldn't be, changes are clean so far

**Pull request merged**
