### PR TITLE
Fix python plugin Json Desterilize issue

### PR DESCRIPTION
**Pull request by taooceros**
#322

### CODE REVIEW

**Review by jjw24 — APPROVED** [review]

**Comment by jjw24** [comment]
you can merge in whenever ready @taooceros

**Comment by taooceros** [comment]
Will do after @deefrawley check it works

**Comment by deefrawley** [comment]
Can someone build me a package/release to test for this and I can test tomorrow morning AEST time? Thanks.

**Comment by jjw24** [comment]
> Can someone build me a package/release to test for this and I can test tomorrow morning AEST time? Thanks.

Yeah it's already done in the issue :)

**Pull request merged**
