### PR TITLE
dev branch: remove createdump.exe

### LINKED ISSUE #479: dev branch: 1.8.0 installation creates a .net shortcut
this shortcut is created everytime 1.8.0 is installed:
image

@taooceros any ideas?

### PR DESCRIPTION
**Pull request by jjw24**
close #479

### CODE REVIEW

**Comment by jjw24** [comment]
@taooceros  getting this error in event viewer and flow does not start after installation:

image

**Comment by taooceros** [comment]
We need to check the dotnet version for CI, which may not be 5.0.6. I am not sure whether there's better way of handling the json modification with powershell.

**Comment by taooceros** [comment]
I change it to regex match, which is simpler and more reliable since it won't depend on the version number.

**Comment by jjw24** [comment]
from the last commit, the shortcut is created again. also issue with parsing the json file:

image

**Comment by taooceros** [comment]
> from the last commit, the shortcut is created again. also issue with parsing the json file:
> 
> image

hmm yes I cannot get it run correctly. By the way, where do you get the log? I am not sure how to debug this kind of issues.

**Comment by jjw24** [comment]
I got it from event viewer, that's usually the place windows log when not caught by apps own exception handler.

Did it work when you manually changed it? If so can u let me know the steps please

**Comment by taooceros** [comment]
> I got it from event viewer, that's usually the place windows log when not caught by apps own exception handler.
> 
> Did it work when you manually changed it? If so can u let me know the steps please

Thanks. Let me take a check.

**Comment by taooceros** [comment]
It will work if I manually change the dep.json. Let me take a comparison of the two file.

**Comment by taooceros** [comment]
I think I know the reason..... powershell will output the file as UTF16, but the dep.json is supposed to be UTF8😣

**Comment by taooceros** [comment]
I think I know the reason..... powershell will output the file as UTF16, but the dep.json is supposed to be UTF8😣

**Comment by jjw24** [comment]
just tested installing, is good 👌 thank you

**Review by taooceros — APPROVED** [review]

**Pull request merged**
