### PR TITLE
Adjust websearch plugin & Small Fix for pluginstore PR & Setting Popup Redesign

### PR DESCRIPTION
**Pull request by onesounds**
This PR for Fix https://github.com/Flow-Launcher/Flow.Launcher/issues/774

- Adjust Websearch Plugin layout
- Adjust Websearch source setting Popup window design & Priority popup window design
  Based fluent design document. 
- Add/Adjust related String

and include https://github.com/Flow-Launcher/Flow.Launcher/pull/776
- Change Hyper link in setting>Theme>Browse more themes
- Add some string
- Fix plugin listbox scrollviewer large bottom space problem when open websearch plugin.

### CODE REVIEW

**Comment by onesounds** [comment]
- Add Guide in setting source popup window
- add Netflix / Youtube music websearch in default list & change order
- add netflix / youtube icon
- Remove Findicon.com

**Comment by onesounds** [comment]
- Adjust CustomQueryHotkey Setting Popup Layout
- Change HotkeyControl to using popup
  - Since the key change confirmation text is displayed on the left or right, it is problem with some layout. so It needed to change. 
  -  Add some code to closing popup when click out of area
   - small problem
     - When dragging a window, the pop-up remains in that position.
     - In the case of special key input (a situation in which an alt is pressed), showing an empty pop-up.

In general situations, there is no problem, and the problem is not critical, so I push it for now. Since the action keyword window modification work remains, it will be modified while continuing to work.

**Comment by onesounds** [comment]
**Before**


**After**


Done. Time to Test.

**Comment by onesounds** [comment]
image

**Review by jjw24 — APPROVED** [review]

**Comment by jjw24** [comment]
it's annoying when you add/remove search sources, because they have to be backwards compatible- for users that already have flow installed the new search sources do not show up, and for removals the action keyword will be retained in the main settings file unless you manually remove it . So lets do them in a seperate pr- https://github.com/Flow-Launcher/Flow.Launcher/pull/787

**Pull request merged**
