### PR TITLE
Release 1.6.0 | Plugin 1.3.1

### PR DESCRIPTION
**Pull request by jjw24**
Release Notes
=========

## Features
- New website https://flow-launcher.github.io #238 
- Enhance Pinyin search, now with more precision when using acronyms #235 
- User made plugins are now available to download: #231, #242, #243
  - Added new PluginsManager plugin for managing the installing, uninstalling and updating of community-made plugins
  - Use hotkeys ```pm install```, ```pm update``` and ```pm uninstall```
  - Have a plugin you would like to share, or making one yourself? Head over to the [PluginsManifest](https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest) repo to submit it
  - Use context menu to go see plugin's website, source code or make an enhancement/bug fix request directly with the plugin developer
  - Archived the old [PluginManagement](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.PluginManagement) plugin
- Improved web connection method for general connections and when via a proxy #178
- [Color](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Color) plugin has been moved out of Flow as a default plugin, and is available for download via `pm install` instead #250
- Added search suggestions from Bing #254 

## Bug Fixes

- Polished up Slovak translation on plugins #216 
- Fixed image flickering on results list #221 
- Fixed Python plugin support via JsonRPC.Python: #225 
  - The Python API is now available via PyPI `pip install flowlauncher`
  - For details of the py support see https://github.com/Flow-Launcher/Flow.Launcher.JsonRPC.Python
- Fixed tray menu translation not updating #223 
- Added notification when version update failed instead of just writing to log #245

### CODE REVIEW

**Comment by jjw24** [comment]
This is going to be a big release, hopefully we can get it out in time for xmas or new yr :) @Flow-Launcher/team

**Comment by jjw24** [comment]
Shall we?

**Comment by taooceros** [comment]
What about #185 hhh?

**Comment by jjw24** [comment]
> What about #185 hhh🤣?

sorry mate, still havent got around to it. It's a core area of the code like the render result list improvement pr, so i really need to thoroughly understand and test the change

**Comment by JohnTheGr8** [comment]
@jjw24 why did we remove installing plugins from file with drag-n-drop?

**Comment by jjw24** [comment]
Doesnt seem like it is needed, didn't even know this functionality existed until i saw the code in the PluginManagement plugin

**Comment by JohnTheGr8** [comment]
> 
> 
> Doesnt seem like it is needed, didn't even know this functionality existed until i saw the code in the PluginManagement plugin

Is there another easy way to quickly test local builds of plugins? That's how I used it, during plugin development...

**Comment by jjw24** [comment]
> > Doesnt seem like it is needed, didn't even know this functionality existed until i saw the code in the PluginManagement plugin
> 
> Is there another easy way to quickly test local builds of plugins? That's how I used it, during plugin development...

can chuck it in userdata's plugin folder and will do the same thing.

**Comment by taooceros** [comment]
> > Doesnt seem like it is needed, didn't even know this functionality existed until i saw the code in the PluginManagement plugin
> 
> Is there another easy way to quickly test local builds of plugins? That's how I used it, during plugin development...

@JohnTheGr8 I think visual studio allow attach to process, so I have tried build a debug version of the plugin and move it to Flow Plugin folder, and run flow, and use VS to debug it via attaching to Flow.

**Comment by taooceros** [comment]
> > What about #185 hhh🤣?
> 
> sorry mate, still havent got around to it. It's a core area of the code like the render result list improvement pr, so i really need to thoroughly understand and test the change

Well I don't think the change in that PR is a lot. I simply add one more loop before the main fuzzy search algorithm to check acronym match, and if match, return it.

**Comment by jjw24** [comment]
yeah no probs i will take a look sometime in the next few days.

**Comment by jjw24** [comment]
Any chance we can get this release moving?

**Comment by taooceros** [comment]
> Any chance we can get this release moving?

I have right checked the usage of the new plugin manager, and I think that we shouldn't simply provide the plugins list when typing "pm", or people won't know that pm can also update or uninstall plugin right?

I think we should display a hotkey list when typing "pm" and provides the result of our plugin list when typing another keyword like "install"?

**Comment by taooceros** [comment]
Sorry for the late catch, and sorry for that I haven't found those issue when reviewing PRs, but something in PluginManager may needs to change.
1. We shouldn't create a new instance of PluginsManager every time in query, which will result in huge query time due to internet transmission. Instead, we should change it to initialize a new instance in Init(). Also, we should do the plugin manifest update every time using install or update keyword, which should be done asynchronously, and updates the result list using event trigger mechanism. This will allow us to quickly return an exist list of plugins to install or update on Init, but also update it every time querying. Or we should have an mechanism like what we have done in Program plugin, that updating that every few hours.
2. I think displaying a hotkeys list when simply typing "pm" will be better than returns the manifest at that time. What do you think @Flow-Launcher/team?

**Comment by taooceros** [comment]
Please check out #249

**Comment by jjw24** [comment]
> Sorry for the late catch, and sorry for that I haven't found those issue when reviewing PRs, but something in PluginManager may needs to change.
> 
> 1. We shouldn't create a new instance of PluginsManager every time in query, which will result in huge query time due to internet transmission. Instead, we should change it to initialize a new instance in Init(). Also, we should do the plugin manifest update every time using install or update keyword, which should be done asynchronously, and updates the result list using event trigger mechanism. This will allow us to quickly return an exist list of plugins to install or update on Init, but also update it every time querying. Or we should have an mechanism like what we have done in Program plugin, that updating that every few hours.
> 2. I think displaying a hotkeys list when simply typing "pm" will be better than returns the manifest at that time. What do you think @Flow-Launcher/team?

all good, i will take a look

**Comment by taooceros** [comment]
Would you please take a look on #178 since currently most of my request toward github has been timeout? Or let me check about whether removing the setting of timeout can solve that issue.

**Comment by jjw24** [comment]
Yeah sure thing, will do now

**Review by taooceros — DISMISSED** [review]
🚀

**Comment by jjw24** [comment]
as a last addition to this release, shall we extract colors plugin and make it available for download via plugins manager?

**Comment by jjw24** [comment]
and a bug fix of post build script #251

**Comment by jjw24** [comment]
Time to rock n roll @Flow-Launcher/team ?

**Review by taooceros — APPROVED** [review]

**Comment by taooceros** [comment]
Since #245 is almost done reviewing, should we include that one in this release as well?

**Comment by jjw24** [comment]
@taooceros shall we?

**Comment by taooceros** [comment]
Yes! Let's go!

**Review by taooceros — APPROVED** [review]

**Pull request merged**
