### PR TITLE
Release 1.16.0 | Plugin 4.1.0

### PR DESCRIPTION
**Pull request by jjw24**
Release Notes
=========

## Features

- Rework how we fetch community plugin data #2222

- Add Czech and Arabic Language Support #2219

- Add Plugin API -> VisibilityChangedEventHandler #2216

- Remove obsolete and unused code #2204

- Added Animation Length slider #2199

- plugin/shell: support Pwsh (PowerShell 7.x) #2183

- Improvements for re-queries #2174

- Consistent handling of clipboard copying #2143

- Add plugin API: HideMainWindow(), IsMainWindowVisible() #2133

- Add sponsor #2118

## Bug fixes

- Switch winget release action to manual #2231

- New Crowdin updates #2215, #2211, #2119

- fix: 🐛 check autocomplete and copy text for Result equality #2202

- Update Plugin documentation #2193

- Bump Microsoft.VisualStudio.Threading from 17.5.22 to 17.6.40 #2187

- Update AppVeyor NuGet API #2180

- Refactor clipboard copying #2177

- Bump Microsoft.NET.Test.Sdk from 17.4.1 to 17.6.1 #2173

- plugin/ProcessKiller: honor "Last Query Style" after kill #2170

- Remove NuGet.CommandLine package dependency #2160

- Bump Microsoft.IO.RecyclableMemoryStream from 2.3.1 to 2.3.2 #2154

- Fix bookmark plugin file monitoring issue #2152

- Add quotes surrounding auto startup entry #2150

- Fix: Add admin permissions when non-admin doesn't work #2149

- Bump Microsoft.VisualStudio.Threading from 17.4.27 to 17.5.22

- Plugin Store search (should) work after refresh button clicked #2137

- Remove deprecated Everything plugin from readme #2127

- Reduce CPU and disk usage during Program plugin init #2123

- Remove unused nuget and imports #2115

### CODE REVIEW

**Comment by JohnTheGr8** [comment]
Thoughts on clearing some (if not all) of the deprecated stuff in the plugin package? Might be a good chance if we're going with a minor update.

**Comment by jjw24** [comment]
Yeah and we should be able to clear out most of the deprecated stuff (including those in main project) as long as they are from several releases back.

**Comment by jjw24** [comment]
Might also be worth excluding spell check on master and dev branches

**Comment by JohnTheGr8** [comment]
@jjw24 should I do it as part of #2193 ? If not, lets get that one in first so we don't have to deal with conflicts.

**Comment by jjw24** [comment]
Let's do it in a separate PR please.

**Comment by JohnTheGr8** [comment]
> Let's do it in a separate PR please.

alright, I have that ready to go in a local branch. To avoid stacking the PRs and re-basing later, I'll wait until #2193 is merged before I open a new PR. Can you have a quick look at it?

**Review by JohnTheGr8 — APPROVED** [review]
🙏

**Pull request merged**
