### PR TITLE
Add forbidden character filter for Explorer plugin

### PR DESCRIPTION
**Pull request by z1nc0r3**
#1771 Forbidden character filter added to Explorer plugin. This only affects when you use the Everything engine as the search engine.

### CODE REVIEW

**Comment by VictoriousRaptor** [comment]
Will it mask Everything's search params?

**Comment by z1nc0r3** [comment]
@VictoriousRaptor Probably not. I tried using different sorting options in **Everything** and the results were accurate. 
_I experienced relatively high memory usage (~200MB) on this version. But I don't know whether it is related to this filter function._

**Comment by VictoriousRaptor** [comment]
> @VictoriousRaptor Probably not. I tried using different sorting options in **Everything** and the results were accurate. _I experienced relatively high memory usage (~200MB) on this version. But I don't know whether it is related to this filter function._

I mean the search functions like `date:xxx` in Everything. Looks like it will break it.

**Comment by taooceros** [comment]
I think we should mask the string on EverythingSearchManager instead of here, since the windows index manager also mask that independently.

**Comment by jjw24** [comment]
> > @VictoriousRaptor Probably not. I tried using different sorting options in **Everything** and the results were accurate. _I experienced relatively high memory usage (~200MB) on this version. But I don't know whether it is related to this filter function._
> 
> I mean the search functions like `date:xxx` in Everything. Looks like it will break it.

Hi @z1nc0r3, please check if this sort of search will still work if you haven't already.

**Comment by jjw24** [comment]
> @VictoriousRaptor Probably not. I tried using different sorting options in **Everything** and the results were accurate. _I experienced relatively high memory usage (~200MB) on this version. But I don't know whether it is related to this filter function._

Is this still the case?

**Comment by jjw24** [comment]
@z1nc0r3 please update description on the tests you have done with this PR.

**Comment by z1nc0r3** [comment]
> > > @VictoriousRaptor Probably not. I tried using different sorting options in **Everything** and the results were accurate. _I experienced relatively high memory usage (~200MB) on this version. But I don't know whether it is related to this filter function._
> > 
> > I mean the search functions like `date:xxx` in Everything. Looks like it will break it.
> 
> Hi @z1nc0r3, please check if this sort of search will still work if you haven't already.

When using `:` for content search is not working on this PR. And the high memory usage is probably a random issue and not related to this logic.

**Comment by jjw24** [comment]
Closed?

**Comment by jjw24** [comment]
Hey @z1nc0r3, are you on our discord? If so please message.

**Comment by z1nc0r3** [comment]
> Closed?

It was by a mistake. I tried to start from scratch to fix the issue and discarded all the commits.

> Hey @z1nc0r3, are you on our discord? If so please message me.

No, I couldn't find the server.

**Comment by jjw24** [comment]
https://discord.gg/AvgAQgh

**Pull request closed without merging**
